// FILE: core/common/src/main/java/com/hereliesaz/graffitixr/common/util/PerspectiveProcessor.kt
package com.hereliesaz.graffitixr.common.util

import android.graphics.Bitmap
import androidx.compose.ui.geometry.Offset
import timber.log.Timber
import org.opencv.android.Utils
import org.opencv.core.CvType
import org.opencv.core.Mat
import org.opencv.core.MatOfPoint2f
import org.opencv.core.Point
import org.opencv.core.Rect
import org.opencv.core.Scalar
import org.opencv.core.Size
import org.opencv.geometry.Geometry
import org.opencv.imgproc.Imgproc

object PerspectiveProcessor {

    init {
        NativeLibLoader.loadAll()
    }

    /**
     * Unwarps an image using a perspective transform based on 4 corner points.
     * Restored to the working method from early project history.
     *
     * @param bitmap The source image.
     * @param points List of 4 Offsets representing the corners in pixel coordinates.
     *               Expected order: TL, TR, BR, BL.
     * @return The unwarped bitmap.
     */
    fun unwarpImage(bitmap: Bitmap, points: List<Offset>): Bitmap? {
        if (points.size != 4) return null

        val mats = mutableListOf<Mat>()
        return try {
            val src = Mat().also { mats.add(it) }
            Utils.bitmapToMat(bitmap, src)

            // Points are passed in TL, TR, BR, BL order by the caller (UnwarpOverlay
            // maintains indexed identity through drag gestures). Do NOT re-sort — a
            // geometric sort by Y/X mis-assigns corners for tilted or rotated quads.
            val tl = points[0]
            val tr = points[1]
            val br = points[2]
            val bl = points[3]

            // Source points
            val srcPoints = MatOfPoint2f(
                Point(tl.x.toDouble(), tl.y.toDouble()),
                Point(tr.x.toDouble(), tr.y.toDouble()),
                Point(br.x.toDouble(), br.y.toDouble()),
                Point(bl.x.toDouble(), bl.y.toDouble())
            ).also { mats.add(it) }

            // Calculate ideal dimensions
            val widthA = Math.sqrt(Math.pow((br.x - bl.x).toDouble(), 2.0) + Math.pow((br.y - bl.y).toDouble(), 2.0))
            val widthB = Math.sqrt(Math.pow((tr.x - tl.x).toDouble(), 2.0) + Math.pow((tr.y - tl.y).toDouble(), 2.0))
            val maxWidth = Math.max(widthA, widthB)

            val heightA = Math.sqrt(Math.pow((tr.x - br.x).toDouble(), 2.0) + Math.pow((tr.y - br.y).toDouble(), 2.0))
            val heightB = Math.sqrt(Math.pow((tl.x - bl.x).toDouble(), 2.0) + Math.pow((tl.y - bl.y).toDouble(), 2.0))
            val maxHeight = Math.max(heightA, heightB)

            // Destination points
            val dstPoints = MatOfPoint2f(
                Point(0.0, 0.0),
                Point(maxWidth, 0.0),
                Point(maxWidth, maxHeight),
                Point(0.0, maxHeight)
            ).also { mats.add(it) }

            val perspectiveTransform = Geometry.getPerspectiveTransform(srcPoints, dstPoints).also { mats.add(it) }
            val dest = Mat().also { mats.add(it) }

            Imgproc.warpPerspective(src, dest, perspectiveTransform, Size(maxWidth, maxHeight))

            val resultBitmap = Bitmap.createBitmap(dest.cols(), dest.rows(), Bitmap.Config.ARGB_8888)
            Utils.matToBitmap(dest, resultBitmap)

            resultBitmap
        } catch (e: Exception) {
            Timber.e(e, "PerspectiveProcessor: processing failed")
            null
        } finally {
            // Release native Mats on every path — they leaked whenever an OpenCV op above threw.
            mats.forEach { it.release() }
        }
    }


    fun removeBackground(bitmap: Bitmap): Bitmap? {
        val mats = mutableListOf<Mat>()
        return try {
            val rgbaMat = Mat().also { mats.add(it) }
            Utils.bitmapToMat(bitmap, rgbaMat)

            val bgrMat = Mat().also { mats.add(it) }
            Imgproc.cvtColor(rgbaMat, bgrMat, Imgproc.COLOR_RGBA2BGR)

            val bgdModel = Mat().also { mats.add(it) }
            val fgdModel = Mat().also { mats.add(it) }
            val mask = Mat(bgrMat.size(), CvType.CV_8UC1, Scalar(Imgproc.GC_BGD.toDouble())).also { mats.add(it) }

            // Leave a 10% margin around the edges, assume the subject is in the center
            val marginX = (bgrMat.cols() * 0.1).toInt()
            val marginY = (bgrMat.rows() * 0.1).toInt()
            val rect = Rect(marginX, marginY, bgrMat.cols() - marginX * 2, bgrMat.rows() - marginY * 2)

            // Run GrabCut algorithm
            Imgproc.grabCut(bgrMat, mask, rect, bgdModel, fgdModel, 5, Imgproc.GC_INIT_WITH_RECT)

            // Extract the foreground markers generated by GrabCut
            val prFgd = Mat(1, 1, CvType.CV_8U, Scalar(Imgproc.GC_PR_FGD.toDouble())).also { mats.add(it) }
            val fgd   = Mat(1, 1, CvType.CV_8U, Scalar(Imgproc.GC_FGD.toDouble())).also { mats.add(it) }

            val finalMask = Mat().also { mats.add(it) }
            org.opencv.core.Core.compare(mask, prFgd, finalMask, org.opencv.core.Core.CMP_EQ)
            val fgMask2 = Mat().also { mats.add(it) }
            org.opencv.core.Core.compare(mask, fgd, fgMask2, org.opencv.core.Core.CMP_EQ)
            org.opencv.core.Core.bitwise_or(finalMask, fgMask2, finalMask)

            // Apply mask to the original RGBA image to preserve transparency
            val outputMat = Mat(rgbaMat.size(), CvType.CV_8UC4, Scalar(0.0, 0.0, 0.0, 0.0)).also { mats.add(it) }
            rgbaMat.copyTo(outputMat, finalMask)

            val outputBitmap = Bitmap.createBitmap(bitmap.width, bitmap.height, Bitmap.Config.ARGB_8888)
            Utils.matToBitmap(outputMat, outputBitmap)

            outputBitmap
        } catch (e: Exception) {
            Timber.e(e, "PerspectiveProcessor: processing failed")
            null
        } finally {
            // Release native Mats on every path — they leaked whenever an OpenCV op above threw.
            mats.forEach { it.release() }
        }
    }
}
