package com.hereliesaz.graffitixr.design

import androidx.annotation.DrawableRes

// Generated by branding/icons/build.py — edit the drawing in branding/icons/masters/, not this file.

/** The families the Graffux icon set is divided into. */
enum class GxIconCategory { TOOLS, SELECTION, LAYERS, COLOR, FILTERS, VECTOR, TYPE, TRANSFORM, DOCUMENT, HISTORY, ANIMATION, GENERATIVE, UI }

/** One icon: its stable key, its drawable, and what it can be searched by. */
data class GxIcon(
    val key: String,
    @param:DrawableRes val res: Int,
    val category: GxIconCategory,
    val keywords: List<String>,
)

/**
 * The Graffux icon set.
 *
 * 404 glyphs on a 24-unit grid at one 0.5-unit stroke weight, outline first.
 * 100 of them rule a region rather than filling it: rows of parallel lines at a fixed
 * pitch, anchored to the viewport rather than to the region, so that any two ruled icons
 * side by side read as ruled from the same plate.
 *
 * Reference them directly (`GraffuxIcons.Brush`) or look them up by key for a picker.
 */
object GraffuxIcons {

    /** `airbrush` — tools. */
    val Airbrush: Int get() = R.drawable.ic_gx_airbrush
    /** `alpha-lock` — tools. */
    val AlphaLock: Int get() = R.drawable.ic_gx_alpha_lock
    /** `blob-brush` — tools. */
    val BlobBrush: Int get() = R.drawable.ic_gx_blob_brush
    /** `blur` — tools. */
    val Blur: Int get() = R.drawable.ic_gx_blur
    /** `brush` — tools. */
    val Brush: Int get() = R.drawable.ic_gx_brush
    /** `brush-angle` — tools. */
    val BrushAngle: Int get() = R.drawable.ic_gx_brush_angle
    /** `brush-flow` — tools. */
    val BrushFlow: Int get() = R.drawable.ic_gx_brush_flow
    /** `brush-hardness` — tools. */
    val BrushHardness: Int get() = R.drawable.ic_gx_brush_hardness
    /** `brush-import` — tools. */
    val BrushImport: Int get() = R.drawable.ic_gx_brush_import
    /** `brush-library` — tools. */
    val BrushLibrary: Int get() = R.drawable.ic_gx_brush_library
    /** `brush-opacity` — tools. */
    val BrushOpacity: Int get() = R.drawable.ic_gx_brush_opacity
    /** `brush-roundness` — tools. */
    val BrushRoundness: Int get() = R.drawable.ic_gx_brush_roundness
    /** `brush-scatter` — tools. */
    val BrushScatter: Int get() = R.drawable.ic_gx_brush_scatter
    /** `brush-settings` — tools. */
    val BrushSettings: Int get() = R.drawable.ic_gx_brush_settings
    /** `brush-size` — tools. */
    val BrushSize: Int get() = R.drawable.ic_gx_brush_size
    /** `brush-spacing` — tools. */
    val BrushSpacing: Int get() = R.drawable.ic_gx_brush_spacing
    /** `brush-texture` — tools. */
    val BrushTexture: Int get() = R.drawable.ic_gx_brush_texture
    /** `burn` — tools. */
    val Burn: Int get() = R.drawable.ic_gx_burn
    /** `calligraphy` — tools. */
    val Calligraphy: Int get() = R.drawable.ic_gx_calligraphy
    /** `chalk` — tools. */
    val Chalk: Int get() = R.drawable.ic_gx_chalk
    /** `charcoal` — tools. */
    val Charcoal: Int get() = R.drawable.ic_gx_charcoal
    /** `colordrop` — tools. */
    val Colordrop: Int get() = R.drawable.ic_gx_colordrop
    /** `crayon` — tools. */
    val Crayon: Int get() = R.drawable.ic_gx_crayon
    /** `dodge` — tools. */
    val Dodge: Int get() = R.drawable.ic_gx_dodge
    /** `eraser` — tools. */
    val Eraser: Int get() = R.drawable.ic_gx_eraser
    /** `eraser-hard` — tools. */
    val EraserHard: Int get() = R.drawable.ic_gx_eraser_hard
    /** `eraser-soft` — tools. */
    val EraserSoft: Int get() = R.drawable.ic_gx_eraser_soft
    /** `eyedropper` — tools. */
    val Eyedropper: Int get() = R.drawable.ic_gx_eyedropper
    /** `fill` — tools. */
    val Fill: Int get() = R.drawable.ic_gx_fill
    /** `guide-drawing` — tools. */
    val GuideDrawing: Int get() = R.drawable.ic_gx_guide_drawing
    /** `guide-isometric` — tools. */
    val GuideIsometric: Int get() = R.drawable.ic_gx_guide_isometric
    /** `guide-perspective` — tools. */
    val GuidePerspective: Int get() = R.drawable.ic_gx_guide_perspective
    /** `heal` — tools. */
    val Heal: Int get() = R.drawable.ic_gx_heal
    /** `heal-spot` — tools. */
    val HealSpot: Int get() = R.drawable.ic_gx_heal_spot
    /** `liquify` — tools. */
    val Liquify: Int get() = R.drawable.ic_gx_liquify
    /** `marker` — tools. */
    val Marker: Int get() = R.drawable.ic_gx_marker
    /** `mixer-brush` — tools. */
    val MixerBrush: Int get() = R.drawable.ic_gx_mixer_brush
    /** `oil-brush` — tools. */
    val OilBrush: Int get() = R.drawable.ic_gx_oil_brush
    /** `patch` — tools. */
    val Patch: Int get() = R.drawable.ic_gx_patch
    /** `pen-ink` — tools. */
    val PenInk: Int get() = R.drawable.ic_gx_pen_ink
    /** `pencil` — tools. */
    val Pencil: Int get() = R.drawable.ic_gx_pencil
    /** `pressure` — tools. */
    val Pressure: Int get() = R.drawable.ic_gx_pressure
    /** `quickshape` — tools. */
    val Quickshape: Int get() = R.drawable.ic_gx_quickshape
    /** `red-eye` — tools. */
    val RedEye: Int get() = R.drawable.ic_gx_red_eye
    /** `roller` — tools. */
    val Roller: Int get() = R.drawable.ic_gx_roller
    /** `sharpen` — tools. */
    val Sharpen: Int get() = R.drawable.ic_gx_sharpen
    /** `smudge` — tools. */
    val Smudge: Int get() = R.drawable.ic_gx_smudge
    /** `sponge` — tools. */
    val Sponge: Int get() = R.drawable.ic_gx_sponge
    /** `spray-can` — tools. */
    val SprayCan: Int get() = R.drawable.ic_gx_spray_can
    /** `stamp` — tools. */
    val Stamp: Int get() = R.drawable.ic_gx_stamp
    /** `stamp-pattern` — tools. */
    val StampPattern: Int get() = R.drawable.ic_gx_stamp_pattern
    /** `streamline` — tools. */
    val Streamline: Int get() = R.drawable.ic_gx_streamline
    /** `stylus` — tools. */
    val Stylus: Int get() = R.drawable.ic_gx_stylus
    /** `symmetry` — tools. */
    val Symmetry: Int get() = R.drawable.ic_gx_symmetry
    /** `symmetry-horizontal` — tools. */
    val SymmetryHorizontal: Int get() = R.drawable.ic_gx_symmetry_horizontal
    /** `symmetry-quadrant` — tools. */
    val SymmetryQuadrant: Int get() = R.drawable.ic_gx_symmetry_quadrant
    /** `symmetry-radial` — tools. */
    val SymmetryRadial: Int get() = R.drawable.ic_gx_symmetry_radial
    /** `symmetry-vertical` — tools. */
    val SymmetryVertical: Int get() = R.drawable.ic_gx_symmetry_vertical
    /** `tilt` — tools. */
    val Tilt: Int get() = R.drawable.ic_gx_tilt
    /** `watercolor` — tools. */
    val Watercolor: Int get() = R.drawable.ic_gx_watercolor
    /** `mask` — selection. */
    val Mask: Int get() = R.drawable.ic_gx_mask
    /** `mask-add` — selection. */
    val MaskAdd: Int get() = R.drawable.ic_gx_mask_add
    /** `mask-apply` — selection. */
    val MaskApply: Int get() = R.drawable.ic_gx_mask_apply
    /** `mask-channel` — selection. */
    val MaskChannel: Int get() = R.drawable.ic_gx_mask_channel
    /** `mask-clipping` — selection. */
    val MaskClipping: Int get() = R.drawable.ic_gx_mask_clipping
    /** `mask-delete` — selection. */
    val MaskDelete: Int get() = R.drawable.ic_gx_mask_delete
    /** `mask-disable` — selection. */
    val MaskDisable: Int get() = R.drawable.ic_gx_mask_disable
    /** `mask-luminance` — selection. */
    val MaskLuminance: Int get() = R.drawable.ic_gx_mask_luminance
    /** `mask-quick` — selection. */
    val MaskQuick: Int get() = R.drawable.ic_gx_mask_quick
    /** `mask-vector` — selection. */
    val MaskVector: Int get() = R.drawable.ic_gx_mask_vector
    /** `select-add` — selection. */
    val SelectAdd: Int get() = R.drawable.ic_gx_select_add
    /** `select-all` — selection. */
    val SelectAll: Int get() = R.drawable.ic_gx_select_all
    /** `select-color-range` — selection. */
    val SelectColorRange: Int get() = R.drawable.ic_gx_select_color_range
    /** `select-ellipse` — selection. */
    val SelectEllipse: Int get() = R.drawable.ic_gx_select_ellipse
    /** `select-exclude` — selection. */
    val SelectExclude: Int get() = R.drawable.ic_gx_select_exclude
    /** `select-feather` — selection. */
    val SelectFeather: Int get() = R.drawable.ic_gx_select_feather
    /** `select-focus` — selection. */
    val SelectFocus: Int get() = R.drawable.ic_gx_select_focus
    /** `select-grow` — selection. */
    val SelectGrow: Int get() = R.drawable.ic_gx_select_grow
    /** `select-intersect` — selection. */
    val SelectIntersect: Int get() = R.drawable.ic_gx_select_intersect
    /** `select-invert` — selection. */
    val SelectInvert: Int get() = R.drawable.ic_gx_select_invert
    /** `select-lasso` — selection. */
    val SelectLasso: Int get() = R.drawable.ic_gx_select_lasso
    /** `select-magnetic` — selection. */
    val SelectMagnetic: Int get() = R.drawable.ic_gx_select_magnetic
    /** `select-none` — selection. */
    val SelectNone: Int get() = R.drawable.ic_gx_select_none
    /** `select-object` — selection. */
    val SelectObject: Int get() = R.drawable.ic_gx_select_object
    /** `select-polygon` — selection. */
    val SelectPolygon: Int get() = R.drawable.ic_gx_select_polygon
    /** `select-quick` — selection. */
    val SelectQuick: Int get() = R.drawable.ic_gx_select_quick
    /** `select-rect` — selection. */
    val SelectRect: Int get() = R.drawable.ic_gx_select_rect
    /** `select-refine` — selection. */
    val SelectRefine: Int get() = R.drawable.ic_gx_select_refine
    /** `select-reselect` — selection. */
    val SelectReselect: Int get() = R.drawable.ic_gx_select_reselect
    /** `select-shrink` — selection. */
    val SelectShrink: Int get() = R.drawable.ic_gx_select_shrink
    /** `select-similar` — selection. */
    val SelectSimilar: Int get() = R.drawable.ic_gx_select_similar
    /** `select-sky` — selection. */
    val SelectSky: Int get() = R.drawable.ic_gx_select_sky
    /** `select-subject` — selection. */
    val SelectSubject: Int get() = R.drawable.ic_gx_select_subject
    /** `select-subtract` — selection. */
    val SelectSubtract: Int get() = R.drawable.ic_gx_select_subtract
    /** `select-transform` — selection. */
    val SelectTransform: Int get() = R.drawable.ic_gx_select_transform
    /** `select-wand` — selection. */
    val SelectWand: Int get() = R.drawable.ic_gx_select_wand
    /** `artboard` — layers. */
    val Artboard: Int get() = R.drawable.ic_gx_artboard
    /** `artboard-add` — layers. */
    val ArtboardAdd: Int get() = R.drawable.ic_gx_artboard_add
    /** `layer-add` — layers. */
    val LayerAdd: Int get() = R.drawable.ic_gx_layer_add
    /** `layer-adjustment` — layers. */
    val LayerAdjustment: Int get() = R.drawable.ic_gx_layer_adjustment
    /** `layer-background` — layers. */
    val LayerBackground: Int get() = R.drawable.ic_gx_layer_background
    /** `layer-blend` — layers. */
    val LayerBlend: Int get() = R.drawable.ic_gx_layer_blend
    /** `layer-count` — layers. */
    val LayerCount: Int get() = R.drawable.ic_gx_layer_count
    /** `layer-delete` — layers. */
    val LayerDelete: Int get() = R.drawable.ic_gx_layer_delete
    /** `layer-duplicate` — layers. */
    val LayerDuplicate: Int get() = R.drawable.ic_gx_layer_duplicate
    /** `layer-fill` — layers. */
    val LayerFill: Int get() = R.drawable.ic_gx_layer_fill
    /** `layer-filter` — layers. */
    val LayerFilter: Int get() = R.drawable.ic_gx_layer_filter
    /** `layer-flatten` — layers. */
    val LayerFlatten: Int get() = R.drawable.ic_gx_layer_flatten
    /** `layer-frame` — layers. */
    val LayerFrame: Int get() = R.drawable.ic_gx_layer_frame
    /** `layer-group` — layers. */
    val LayerGroup: Int get() = R.drawable.ic_gx_layer_group
    /** `layer-hidden` — layers. */
    val LayerHidden: Int get() = R.drawable.ic_gx_layer_hidden
    /** `layer-isolate` — layers. */
    val LayerIsolate: Int get() = R.drawable.ic_gx_layer_isolate
    /** `layer-link` — layers. */
    val LayerLink: Int get() = R.drawable.ic_gx_layer_link
    /** `layer-lock` — layers. */
    val LayerLock: Int get() = R.drawable.ic_gx_layer_lock
    /** `layer-lower` — layers. */
    val LayerLower: Int get() = R.drawable.ic_gx_layer_lower
    /** `layer-merge-down` — layers. */
    val LayerMergeDown: Int get() = R.drawable.ic_gx_layer_merge_down
    /** `layer-merge-visible` — layers. */
    val LayerMergeVisible: Int get() = R.drawable.ic_gx_layer_merge_visible
    /** `layer-opacity` — layers. */
    val LayerOpacity: Int get() = R.drawable.ic_gx_layer_opacity
    /** `layer-raise` — layers. */
    val LayerRaise: Int get() = R.drawable.ic_gx_layer_raise
    /** `layer-rasterize` — layers. */
    val LayerRasterize: Int get() = R.drawable.ic_gx_layer_rasterize
    /** `layer-reference` — layers. */
    val LayerReference: Int get() = R.drawable.ic_gx_layer_reference
    /** `layer-rename` — layers. */
    val LayerRename: Int get() = R.drawable.ic_gx_layer_rename
    /** `layer-smart` — layers. */
    val LayerSmart: Int get() = R.drawable.ic_gx_layer_smart
    /** `layer-style` — layers. */
    val LayerStyle: Int get() = R.drawable.ic_gx_layer_style
    /** `layer-tag` — layers. */
    val LayerTag: Int get() = R.drawable.ic_gx_layer_tag
    /** `layer-thumbnail` — layers. */
    val LayerThumbnail: Int get() = R.drawable.ic_gx_layer_thumbnail
    /** `layer-to-back` — layers. */
    val LayerToBack: Int get() = R.drawable.ic_gx_layer_to_back
    /** `layer-to-front` — layers. */
    val LayerToFront: Int get() = R.drawable.ic_gx_layer_to_front
    /** `layer-ungroup` — layers. */
    val LayerUngroup: Int get() = R.drawable.ic_gx_layer_ungroup
    /** `layer-unlink` — layers. */
    val LayerUnlink: Int get() = R.drawable.ic_gx_layer_unlink
    /** `layer-unlock` — layers. */
    val LayerUnlock: Int get() = R.drawable.ic_gx_layer_unlock
    /** `layer-visible` — layers. */
    val LayerVisible: Int get() = R.drawable.ic_gx_layer_visible
    /** `layers` — layers. */
    val Layers: Int get() = R.drawable.ic_gx_layers
    /** `auto-tone` — color. */
    val AutoTone: Int get() = R.drawable.ic_gx_auto_tone
    /** `black-white` — color. */
    val BlackWhite: Int get() = R.drawable.ic_gx_black_white
    /** `brightness` — color. */
    val Brightness: Int get() = R.drawable.ic_gx_brightness
    /** `channel-mixer` — color. */
    val ChannelMixer: Int get() = R.drawable.ic_gx_channel_mixer
    /** `clarity` — color. */
    val Clarity: Int get() = R.drawable.ic_gx_clarity
    /** `color-alpha` — color. */
    val ColorAlpha: Int get() = R.drawable.ic_gx_color_alpha
    /** `color-balance` — color. */
    val ColorBalance: Int get() = R.drawable.ic_gx_color_balance
    /** `color-cmyk` — color. */
    val ColorCmyk: Int get() = R.drawable.ic_gx_color_cmyk
    /** `color-disc` — color. */
    val ColorDisc: Int get() = R.drawable.ic_gx_color_disc
    /** `color-harmony` — color. */
    val ColorHarmony: Int get() = R.drawable.ic_gx_color_harmony
    /** `color-hex` — color. */
    val ColorHex: Int get() = R.drawable.ic_gx_color_hex
    /** `color-history` — color. */
    val ColorHistory: Int get() = R.drawable.ic_gx_color_history
    /** `color-lookup` — color. */
    val ColorLookup: Int get() = R.drawable.ic_gx_color_lookup
    /** `color-profile` — color. */
    val ColorProfile: Int get() = R.drawable.ic_gx_color_profile
    /** `color-rgb` — color. */
    val ColorRgb: Int get() = R.drawable.ic_gx_color_rgb
    /** `color-swatch` — color. */
    val ColorSwatch: Int get() = R.drawable.ic_gx_color_swatch
    /** `color-swatches` — color. */
    val ColorSwatches: Int get() = R.drawable.ic_gx_color_swatches
    /** `contrast` — color. */
    val Contrast: Int get() = R.drawable.ic_gx_contrast
    /** `curves` — color. */
    val Curves: Int get() = R.drawable.ic_gx_curves
    /** `desaturate` — color. */
    val Desaturate: Int get() = R.drawable.ic_gx_desaturate
    /** `exposure` — color. */
    val Exposure: Int get() = R.drawable.ic_gx_exposure
    /** `gradient` — color. */
    val Gradient: Int get() = R.drawable.ic_gx_gradient
    /** `gradient-angle` — color. */
    val GradientAngle: Int get() = R.drawable.ic_gx_gradient_angle
    /** `gradient-linear` — color. */
    val GradientLinear: Int get() = R.drawable.ic_gx_gradient_linear
    /** `gradient-map` — color. */
    val GradientMap: Int get() = R.drawable.ic_gx_gradient_map
    /** `gradient-mesh` — color. */
    val GradientMesh: Int get() = R.drawable.ic_gx_gradient_mesh
    /** `gradient-radial` — color. */
    val GradientRadial: Int get() = R.drawable.ic_gx_gradient_radial
    /** `grain` — color. */
    val Grain: Int get() = R.drawable.ic_gx_grain
    /** `histogram` — color. */
    val Histogram: Int get() = R.drawable.ic_gx_histogram
    /** `hue` — color. */
    val Hue: Int get() = R.drawable.ic_gx_hue
    /** `invert` — color. */
    val Invert: Int get() = R.drawable.ic_gx_invert
    /** `levels` — color. */
    val Levels: Int get() = R.drawable.ic_gx_levels
    /** `photo-filter` — color. */
    val PhotoFilter: Int get() = R.drawable.ic_gx_photo_filter
    /** `posterize` — color. */
    val Posterize: Int get() = R.drawable.ic_gx_posterize
    /** `replace-color` — color. */
    val ReplaceColor: Int get() = R.drawable.ic_gx_replace_color
    /** `saturation` — color. */
    val Saturation: Int get() = R.drawable.ic_gx_saturation
    /** `selective-color` — color. */
    val SelectiveColor: Int get() = R.drawable.ic_gx_selective_color
    /** `shadows-highlights` — color. */
    val ShadowsHighlights: Int get() = R.drawable.ic_gx_shadows_highlights
    /** `temperature` — color. */
    val Temperature: Int get() = R.drawable.ic_gx_temperature
    /** `threshold` — color. */
    val Threshold: Int get() = R.drawable.ic_gx_threshold
    /** `tint` — color. */
    val Tint: Int get() = R.drawable.ic_gx_tint
    /** `vibrance` — color. */
    val Vibrance: Int get() = R.drawable.ic_gx_vibrance
    /** `vignette` — color. */
    val Vignette: Int get() = R.drawable.ic_gx_vignette
    /** `filter-bevel` — filters. */
    val FilterBevel: Int get() = R.drawable.ic_gx_filter_bevel
    /** `filter-blur-gaussian` — filters. */
    val FilterBlurGaussian: Int get() = R.drawable.ic_gx_filter_blur_gaussian
    /** `filter-blur-lens` — filters. */
    val FilterBlurLens: Int get() = R.drawable.ic_gx_filter_blur_lens
    /** `filter-blur-motion` — filters. */
    val FilterBlurMotion: Int get() = R.drawable.ic_gx_filter_blur_motion
    /** `filter-blur-radial` — filters. */
    val FilterBlurRadial: Int get() = R.drawable.ic_gx_filter_blur_radial
    /** `filter-clone-source` — filters. */
    val FilterCloneSource: Int get() = R.drawable.ic_gx_filter_clone_source
    /** `filter-content-aware-fill` — filters. */
    val FilterContentAwareFill: Int get() = R.drawable.ic_gx_filter_content_aware_fill
    /** `filter-crystallize` — filters. */
    val FilterCrystallize: Int get() = R.drawable.ic_gx_filter_crystallize
    /** `filter-distort-pinch` — filters. */
    val FilterDistortPinch: Int get() = R.drawable.ic_gx_filter_distort_pinch
    /** `filter-distort-spherize` — filters. */
    val FilterDistortSpherize: Int get() = R.drawable.ic_gx_filter_distort_spherize
    /** `filter-distort-twirl` — filters. */
    val FilterDistortTwirl: Int get() = R.drawable.ic_gx_filter_distort_twirl
    /** `filter-distort-wave` — filters. */
    val FilterDistortWave: Int get() = R.drawable.ic_gx_filter_distort_wave
    /** `filter-emboss` — filters. */
    val FilterEmboss: Int get() = R.drawable.ic_gx_filter_emboss
    /** `filter-gallery` — filters. */
    val FilterGallery: Int get() = R.drawable.ic_gx_filter_gallery
    /** `filter-generative-fill` — filters. */
    val FilterGenerativeFill: Int get() = R.drawable.ic_gx_filter_generative_fill
    /** `filter-glow` — filters. */
    val FilterGlow: Int get() = R.drawable.ic_gx_filter_glow
    /** `filter-halftone` — filters. */
    val FilterHalftone: Int get() = R.drawable.ic_gx_filter_halftone
    /** `filter-lens-flare` — filters. */
    val FilterLensFlare: Int get() = R.drawable.ic_gx_filter_lens_flare
    /** `filter-liquify` — filters. */
    val FilterLiquify: Int get() = R.drawable.ic_gx_filter_liquify
    /** `filter-mosaic` — filters. */
    val FilterMosaic: Int get() = R.drawable.ic_gx_filter_mosaic
    /** `filter-noise-add` — filters. */
    val FilterNoiseAdd: Int get() = R.drawable.ic_gx_filter_noise_add
    /** `filter-noise-reduce` — filters. */
    val FilterNoiseReduce: Int get() = R.drawable.ic_gx_filter_noise_reduce
    /** `filter-render-clouds` — filters. */
    val FilterRenderClouds: Int get() = R.drawable.ic_gx_filter_render_clouds
    /** `filter-shadow-drop` — filters. */
    val FilterShadowDrop: Int get() = R.drawable.ic_gx_filter_shadow_drop
    /** `filter-shadow-inner` — filters. */
    val FilterShadowInner: Int get() = R.drawable.ic_gx_filter_shadow_inner
    /** `filter-sharpen-unsharp` — filters. */
    val FilterSharpenUnsharp: Int get() = R.drawable.ic_gx_filter_sharpen_unsharp
    /** `filter-sky-replace` — filters. */
    val FilterSkyReplace: Int get() = R.drawable.ic_gx_filter_sky_replace
    /** `filter-smart-radius` — filters. */
    val FilterSmartRadius: Int get() = R.drawable.ic_gx_filter_smart_radius
    /** `filter-stroke-outline` — filters. */
    val FilterStrokeOutline: Int get() = R.drawable.ic_gx_filter_stroke_outline
    /** `filter-vanishing-point` — filters. */
    val FilterVanishingPoint: Int get() = R.drawable.ic_gx_filter_vanishing_point
    /** `filter-vignette-post` — filters. */
    val FilterVignettePost: Int get() = R.drawable.ic_gx_filter_vignette_post
    /** `anchor-convert` — vector. */
    val AnchorConvert: Int get() = R.drawable.ic_gx_anchor_convert
    /** `boolean-exclude` — vector. */
    val BooleanExclude: Int get() = R.drawable.ic_gx_boolean_exclude
    /** `boolean-intersect` — vector. */
    val BooleanIntersect: Int get() = R.drawable.ic_gx_boolean_intersect
    /** `boolean-minus` — vector. */
    val BooleanMinus: Int get() = R.drawable.ic_gx_boolean_minus
    /** `boolean-unite` — vector. */
    val BooleanUnite: Int get() = R.drawable.ic_gx_boolean_unite
    /** `clipping-mask-vector` — vector. */
    val ClippingMaskVector: Int get() = R.drawable.ic_gx_clipping_mask_vector
    /** `compound-path` — vector. */
    val CompoundPath: Int get() = R.drawable.ic_gx_compound_path
    /** `guide-ruler` — vector. */
    val GuideRuler: Int get() = R.drawable.ic_gx_guide_ruler
    /** `handle-asymmetric` — vector. */
    val HandleAsymmetric: Int get() = R.drawable.ic_gx_handle_asymmetric
    /** `handle-symmetric` — vector. */
    val HandleSymmetric: Int get() = R.drawable.ic_gx_handle_symmetric
    /** `path-close` — vector. */
    val PathClose: Int get() = R.drawable.ic_gx_path_close
    /** `path-eraser-vector` — vector. */
    val PathEraserVector: Int get() = R.drawable.ic_gx_path_eraser_vector
    /** `path-knife` — vector. */
    val PathKnife: Int get() = R.drawable.ic_gx_path_knife
    /** `path-offset` — vector. */
    val PathOffset: Int get() = R.drawable.ic_gx_path_offset
    /** `path-open` — vector. */
    val PathOpen: Int get() = R.drawable.ic_gx_path_open
    /** `path-outline-stroke` — vector. */
    val PathOutlineStroke: Int get() = R.drawable.ic_gx_path_outline_stroke
    /** `path-reverse` — vector. */
    val PathReverse: Int get() = R.drawable.ic_gx_path_reverse
    /** `path-select-direct` — vector. */
    val PathSelectDirect: Int get() = R.drawable.ic_gx_path_select_direct
    /** `path-select-group` — vector. */
    val PathSelectGroup: Int get() = R.drawable.ic_gx_path_select_group
    /** `path-simplify` — vector. */
    val PathSimplify: Int get() = R.drawable.ic_gx_path_simplify
    /** `path-width` — vector. */
    val PathWidth: Int get() = R.drawable.ic_gx_path_width
    /** `pen` — vector. */
    val Pen: Int get() = R.drawable.ic_gx_pen
    /** `pen-add` — vector. */
    val PenAdd: Int get() = R.drawable.ic_gx_pen_add
    /** `pen-remove` — vector. */
    val PenRemove: Int get() = R.drawable.ic_gx_pen_remove
    /** `shape-line` — vector. */
    val ShapeLine: Int get() = R.drawable.ic_gx_shape_line
    /** `shape-polygon` — vector. */
    val ShapePolygon: Int get() = R.drawable.ic_gx_shape_polygon
    /** `shape-rectangle` — vector. */
    val ShapeRectangle: Int get() = R.drawable.ic_gx_shape_rectangle
    /** `shape-spiral` — vector. */
    val ShapeSpiral: Int get() = R.drawable.ic_gx_shape_spiral
    /** `shape-star` — vector. */
    val ShapeStar: Int get() = R.drawable.ic_gx_shape_star
    /** `trace-image` — vector. */
    val TraceImage: Int get() = R.drawable.ic_gx_trace_image
    /** `vectorize` — vector. */
    val Vectorize: Int get() = R.drawable.ic_gx_vectorize
    /** `baseline-shift` — type. */
    val BaselineShift: Int get() = R.drawable.ic_gx_baseline_shift
    /** `find-replace-text` — type. */
    val FindReplaceText: Int get() = R.drawable.ic_gx_find_replace_text
    /** `font-family` — type. */
    val FontFamily: Int get() = R.drawable.ic_gx_font_family
    /** `font-size` — type. */
    val FontSize: Int get() = R.drawable.ic_gx_font_size
    /** `font-weight` — type. */
    val FontWeight: Int get() = R.drawable.ic_gx_font_weight
    /** `glyphs-panel` — type. */
    val GlyphsPanel: Int get() = R.drawable.ic_gx_glyphs_panel
    /** `kerning` — type. */
    val Kerning: Int get() = R.drawable.ic_gx_kerning
    /** `leading` — type. */
    val Leading: Int get() = R.drawable.ic_gx_leading
    /** `paragraph-align-center` — type. */
    val ParagraphAlignCenter: Int get() = R.drawable.ic_gx_paragraph_align_center
    /** `paragraph-align-left` — type. */
    val ParagraphAlignLeft: Int get() = R.drawable.ic_gx_paragraph_align_left
    /** `paragraph-align-right` — type. */
    val ParagraphAlignRight: Int get() = R.drawable.ic_gx_paragraph_align_right
    /** `paragraph-indent` — type. */
    val ParagraphIndent: Int get() = R.drawable.ic_gx_paragraph_indent
    /** `paragraph-justify` — type. */
    val ParagraphJustify: Int get() = R.drawable.ic_gx_paragraph_justify
    /** `spell-check` — type. */
    val SpellCheck: Int get() = R.drawable.ic_gx_spell_check
    /** `text-color` — type. */
    val TextColor: Int get() = R.drawable.ic_gx_text_color
    /** `text-outline-convert` — type. */
    val TextOutlineConvert: Int get() = R.drawable.ic_gx_text_outline_convert
    /** `tracking` — type. */
    val Tracking: Int get() = R.drawable.ic_gx_tracking
    /** `type` — type. */
    val Type: Int get() = R.drawable.ic_gx_type
    /** `type-allcaps` — type. */
    val TypeAllcaps: Int get() = R.drawable.ic_gx_type_allcaps
    /** `type-area` — type. */
    val TypeArea: Int get() = R.drawable.ic_gx_type_area
    /** `type-bold` — type. */
    val TypeBold: Int get() = R.drawable.ic_gx_type_bold
    /** `type-italic` — type. */
    val TypeItalic: Int get() = R.drawable.ic_gx_type_italic
    /** `type-mask` — type. */
    val TypeMask: Int get() = R.drawable.ic_gx_type_mask
    /** `type-path` — type. */
    val TypePath: Int get() = R.drawable.ic_gx_type_path
    /** `type-point` — type. */
    val TypePoint: Int get() = R.drawable.ic_gx_type_point
    /** `type-strikethrough` — type. */
    val TypeStrikethrough: Int get() = R.drawable.ic_gx_type_strikethrough
    /** `type-subscript` — type. */
    val TypeSubscript: Int get() = R.drawable.ic_gx_type_subscript
    /** `type-superscript` — type. */
    val TypeSuperscript: Int get() = R.drawable.ic_gx_type_superscript
    /** `type-underline` — type. */
    val TypeUnderline: Int get() = R.drawable.ic_gx_type_underline
    /** `type-vertical` — type. */
    val TypeVertical: Int get() = R.drawable.ic_gx_type_vertical
    /** `type-warp` — type. */
    val TypeWarp: Int get() = R.drawable.ic_gx_type_warp
    /** `align-bottom` — transform. */
    val AlignBottom: Int get() = R.drawable.ic_gx_align_bottom
    /** `align-center-h` — transform. */
    val AlignCenterH: Int get() = R.drawable.ic_gx_align_center_h
    /** `align-left` — transform. */
    val AlignLeft: Int get() = R.drawable.ic_gx_align_left
    /** `align-middle-v` — transform. */
    val AlignMiddleV: Int get() = R.drawable.ic_gx_align_middle_v
    /** `align-right` — transform. */
    val AlignRight: Int get() = R.drawable.ic_gx_align_right
    /** `align-to-artboard` — transform. */
    val AlignToArtboard: Int get() = R.drawable.ic_gx_align_to_artboard
    /** `align-top` — transform. */
    val AlignTop: Int get() = R.drawable.ic_gx_align_top
    /** `distort` — transform. */
    val Distort: Int get() = R.drawable.ic_gx_distort
    /** `distribute-horizontal` — transform. */
    val DistributeHorizontal: Int get() = R.drawable.ic_gx_distribute_horizontal
    /** `distribute-vertical` — transform. */
    val DistributeVertical: Int get() = R.drawable.ic_gx_distribute_vertical
    /** `flip-horizontal` — transform. */
    val FlipHorizontal: Int get() = R.drawable.ic_gx_flip_horizontal
    /** `flip-vertical` — transform. */
    val FlipVertical: Int get() = R.drawable.ic_gx_flip_vertical
    /** `move` — transform. */
    val Move: Int get() = R.drawable.ic_gx_move
    /** `perspective-transform` — transform. */
    val PerspectiveTransform: Int get() = R.drawable.ic_gx_perspective_transform
    /** `puppet-warp` — transform. */
    val PuppetWarp: Int get() = R.drawable.ic_gx_puppet_warp
    /** `reset-transform` — transform. */
    val ResetTransform: Int get() = R.drawable.ic_gx_reset_transform
    /** `rotate` — transform. */
    val Rotate: Int get() = R.drawable.ic_gx_rotate
    /** `rotate-180` — transform. */
    val Rotate180: Int get() = R.drawable.ic_gx_rotate_180
    /** `rotate-90-ccw` — transform. */
    val Rotate90Ccw: Int get() = R.drawable.ic_gx_rotate_90_ccw
    /** `rotate-90-cw` — transform. */
    val Rotate90Cw: Int get() = R.drawable.ic_gx_rotate_90_cw
    /** `scale` — transform. */
    val Scale: Int get() = R.drawable.ic_gx_scale
    /** `scale-proportional` — transform. */
    val ScaleProportional: Int get() = R.drawable.ic_gx_scale_proportional
    /** `skew` — transform. */
    val Skew: Int get() = R.drawable.ic_gx_skew
    /** `smart-guides` — transform. */
    val SmartGuides: Int get() = R.drawable.ic_gx_smart_guides
    /** `snap-to-grid` — transform. */
    val SnapToGrid: Int get() = R.drawable.ic_gx_snap_to_grid
    /** `transform-again` — transform. */
    val TransformAgain: Int get() = R.drawable.ic_gx_transform_again
    /** `bleed-marks` — document. */
    val BleedMarks: Int get() = R.drawable.ic_gx_bleed_marks
    /** `canvas-size` — document. */
    val CanvasSize: Int get() = R.drawable.ic_gx_canvas_size
    /** `crop` — document. */
    val Crop: Int get() = R.drawable.ic_gx_crop
    /** `crop-straighten` — document. */
    val CropStraighten: Int get() = R.drawable.ic_gx_crop_straighten
    /** `document-close` — document. */
    val DocumentClose: Int get() = R.drawable.ic_gx_document_close
    /** `document-new` — document. */
    val DocumentNew: Int get() = R.drawable.ic_gx_document_new
    /** `document-open` — document. */
    val DocumentOpen: Int get() = R.drawable.ic_gx_document_open
    /** `document-properties` — document. */
    val DocumentProperties: Int get() = R.drawable.ic_gx_document_properties
    /** `document-revert` — document. */
    val DocumentRevert: Int get() = R.drawable.ic_gx_document_revert
    /** `document-save` — document. */
    val DocumentSave: Int get() = R.drawable.ic_gx_document_save
    /** `document-save-as` — document. */
    val DocumentSaveAs: Int get() = R.drawable.ic_gx_document_save_as
    /** `full-screen` — document. */
    val FullScreen: Int get() = R.drawable.ic_gx_full_screen
    /** `grid-overlay` — document. */
    val GridOverlay: Int get() = R.drawable.ic_gx_grid_overlay
    /** `guides` — document. */
    val Guides: Int get() = R.drawable.ic_gx_guides
    /** `image-size` — document. */
    val ImageSize: Int get() = R.drawable.ic_gx_image_size
    /** `multi-window` — document. */
    val MultiWindow: Int get() = R.drawable.ic_gx_multi_window
    /** `pan-hand` — document. */
    val PanHand: Int get() = R.drawable.ic_gx_pan_hand
    /** `resample` — document. */
    val Resample: Int get() = R.drawable.ic_gx_resample
    /** `rotate-view` — document. */
    val RotateView: Int get() = R.drawable.ic_gx_rotate_view
    /** `rulers` — document. */
    val Rulers: Int get() = R.drawable.ic_gx_rulers
    /** `split-view` — document. */
    val SplitView: Int get() = R.drawable.ic_gx_split_view
    /** `thumbnails` — document. */
    val Thumbnails: Int get() = R.drawable.ic_gx_thumbnails
    /** `view-actual-colors` — document. */
    val ViewActualColors: Int get() = R.drawable.ic_gx_view_actual_colors
    /** `view-cmyk-preview` — document. */
    val ViewCmykPreview: Int get() = R.drawable.ic_gx_view_cmyk_preview
    /** `zoom-100` — document. */
    val Zoom100: Int get() = R.drawable.ic_gx_zoom_100
    /** `zoom-fit` — document. */
    val ZoomFit: Int get() = R.drawable.ic_gx_zoom_fit
    /** `zoom-in` — document. */
    val ZoomIn: Int get() = R.drawable.ic_gx_zoom_in
    /** `zoom-out` — document. */
    val ZoomOut: Int get() = R.drawable.ic_gx_zoom_out
    /** `action-play` — history. */
    val ActionPlay: Int get() = R.drawable.ic_gx_action_play
    /** `action-record` — history. */
    val ActionRecord: Int get() = R.drawable.ic_gx_action_record
    /** `action-stop` — history. */
    val ActionStop: Int get() = R.drawable.ic_gx_action_stop
    /** `actions-panel` — history. */
    val ActionsPanel: Int get() = R.drawable.ic_gx_actions_panel
    /** `batch-process` — history. */
    val BatchProcess: Int get() = R.drawable.ic_gx_batch_process
    /** `checkpoint-restore` — history. */
    val CheckpointRestore: Int get() = R.drawable.ic_gx_checkpoint_restore
    /** `clear-history` — history. */
    val ClearHistory: Int get() = R.drawable.ic_gx_clear_history
    /** `history-brush` — history. */
    val HistoryBrush: Int get() = R.drawable.ic_gx_history_brush
    /** `history-panel` — history. */
    val HistoryPanel: Int get() = R.drawable.ic_gx_history_panel
    /** `history-snapshot` — history. */
    val HistorySnapshot: Int get() = R.drawable.ic_gx_history_snapshot
    /** `redo` — history. */
    val Redo: Int get() = R.drawable.ic_gx_redo
    /** `timer` — history. */
    val Timer: Int get() = R.drawable.ic_gx_timer
    /** `undo` — history. */
    val Undo: Int get() = R.drawable.ic_gx_undo
    /** `version-compare` — history. */
    val VersionCompare: Int get() = R.drawable.ic_gx_version_compare
    /** `export-gif` — animation. */
    val ExportGif: Int get() = R.drawable.ic_gx_export_gif
    /** `export-video` — animation. */
    val ExportVideo: Int get() = R.drawable.ic_gx_export_video
    /** `frame-add` — animation. */
    val FrameAdd: Int get() = R.drawable.ic_gx_frame_add
    /** `frame-delete` — animation. */
    val FrameDelete: Int get() = R.drawable.ic_gx_frame_delete
    /** `frame-duplicate` — animation. */
    val FrameDuplicate: Int get() = R.drawable.ic_gx_frame_duplicate
    /** `frame-rate` — animation. */
    val FrameRate: Int get() = R.drawable.ic_gx_frame_rate
    /** `keyframe` — animation. */
    val Keyframe: Int get() = R.drawable.ic_gx_keyframe
    /** `keyframe-add` — animation. */
    val KeyframeAdd: Int get() = R.drawable.ic_gx_keyframe_add
    /** `loop-playback` — animation. */
    val LoopPlayback: Int get() = R.drawable.ic_gx_loop_playback
    /** `motion-tween` — animation. */
    val MotionTween: Int get() = R.drawable.ic_gx_motion_tween
    /** `onion-skin` — animation. */
    val OnionSkin: Int get() = R.drawable.ic_gx_onion_skin
    /** `pause` — animation. */
    val Pause: Int get() = R.drawable.ic_gx_pause
    /** `play` — animation. */
    val Play: Int get() = R.drawable.ic_gx_play
    /** `step-backward` — animation. */
    val StepBackward: Int get() = R.drawable.ic_gx_step_backward
    /** `step-forward` — animation. */
    val StepForward: Int get() = R.drawable.ic_gx_step_forward
    /** `stop` — animation. */
    val Stop: Int get() = R.drawable.ic_gx_stop
    /** `timeline` — animation. */
    val Timeline: Int get() = R.drawable.ic_gx_timeline
    /** `ar-view` — generative. */
    val ArView: Int get() = R.drawable.ic_gx_ar_view
    /** `camera-capture` — generative. */
    val CameraCapture: Int get() = R.drawable.ic_gx_camera_capture
    /** `edge-detect` — generative. */
    val EdgeDetect: Int get() = R.drawable.ic_gx_edge_detect
    /** `gallery-import` — generative. */
    val GalleryImport: Int get() = R.drawable.ic_gx_gallery_import
    /** `generate` — generative. */
    val Generate: Int get() = R.drawable.ic_gx_generate
    /** `generate-expand` — generative. */
    val GenerateExpand: Int get() = R.drawable.ic_gx_generate_expand
    /** `generate-remove` — generative. */
    val GenerateRemove: Int get() = R.drawable.ic_gx_generate_remove
    /** `generate-variations` — generative. */
    val GenerateVariations: Int get() = R.drawable.ic_gx_generate_variations
    /** `mural-scale` — generative. */
    val MuralScale: Int get() = R.drawable.ic_gx_mural_scale
    /** `prompt` — generative. */
    val Prompt: Int get() = R.drawable.ic_gx_prompt
    /** `registration-mark` — generative. */
    val RegistrationMark: Int get() = R.drawable.ic_gx_registration_mark
    /** `stencil` — generative. */
    val Stencil: Int get() = R.drawable.ic_gx_stencil
    /** `stencil-layers` — generative. */
    val StencilLayers: Int get() = R.drawable.ic_gx_stencil_layers
    /** `style-transfer` — generative. */
    val StyleTransfer: Int get() = R.drawable.ic_gx_style_transfer
    /** `subject-isolate` — generative. */
    val SubjectIsolate: Int get() = R.drawable.ic_gx_subject_isolate
    /** `upscale` — generative. */
    val Upscale: Int get() = R.drawable.ic_gx_upscale
    /** `account` — ui. */
    val Account: Int get() = R.drawable.ic_gx_account
    /** `back` — ui. */
    val Back: Int get() = R.drawable.ic_gx_back
    /** `brush-cursor` — ui. */
    val BrushCursor: Int get() = R.drawable.ic_gx_brush_cursor
    /** `chevron-down` — ui. */
    val ChevronDown: Int get() = R.drawable.ic_gx_chevron_down
    /** `chevron-up` — ui. */
    val ChevronUp: Int get() = R.drawable.ic_gx_chevron_up
    /** `close` — ui. */
    val Close: Int get() = R.drawable.ic_gx_close
    /** `cloud-offline` — ui. */
    val CloudOffline: Int get() = R.drawable.ic_gx_cloud_offline
    /** `cloud-sync` — ui. */
    val CloudSync: Int get() = R.drawable.ic_gx_cloud_sync
    /** `collaborators` — ui. */
    val Collaborators: Int get() = R.drawable.ic_gx_collaborators
    /** `comment` — ui. */
    val Comment: Int get() = R.drawable.ic_gx_comment
    /** `copy-link` — ui. */
    val CopyLink: Int get() = R.drawable.ic_gx_copy_link
    /** `download` — ui. */
    val Download: Int get() = R.drawable.ic_gx_download
    /** `error` — ui. */
    val Error: Int get() = R.drawable.ic_gx_error
    /** `forward` — ui. */
    val Forward: Int get() = R.drawable.ic_gx_forward
    /** `gesture-pinch` — ui. */
    val GesturePinch: Int get() = R.drawable.ic_gx_gesture_pinch
    /** `gesture-two-finger-tap` — ui. */
    val GestureTwoFingerTap: Int get() = R.drawable.ic_gx_gesture_two_finger_tap
    /** `help` — ui. */
    val Help: Int get() = R.drawable.ic_gx_help
    /** `info` — ui. */
    val Info: Int get() = R.drawable.ic_gx_info
    /** `keyboard-shortcut` — ui. */
    val KeyboardShortcut: Int get() = R.drawable.ic_gx_keyboard_shortcut
    /** `language` — ui. */
    val Language: Int get() = R.drawable.ic_gx_language
    /** `link-external` — ui. */
    val LinkExternal: Int get() = R.drawable.ic_gx_link_external
    /** `menu` — ui. */
    val Menu: Int get() = R.drawable.ic_gx_menu
    /** `more-horizontal` — ui. */
    val MoreHorizontal: Int get() = R.drawable.ic_gx_more_horizontal
    /** `more-vertical` — ui. */
    val MoreVertical: Int get() = R.drawable.ic_gx_more_vertical
    /** `notification` — ui. */
    val Notification: Int get() = R.drawable.ic_gx_notification
    /** `search` — ui. */
    val Search: Int get() = R.drawable.ic_gx_search
    /** `settings` — ui. */
    val Settings: Int get() = R.drawable.ic_gx_settings
    /** `share` — ui. */
    val Share: Int get() = R.drawable.ic_gx_share
    /** `subscription` — ui. */
    val Subscription: Int get() = R.drawable.ic_gx_subscription
    /** `success` — ui. */
    val Success: Int get() = R.drawable.ic_gx_success
    /** `theme-toggle` — ui. */
    val ThemeToggle: Int get() = R.drawable.ic_gx_theme_toggle
    /** `undo-history-slider` — ui. */
    val UndoHistorySlider: Int get() = R.drawable.ic_gx_undo_history_slider
    /** `upload` — ui. */
    val Upload: Int get() = R.drawable.ic_gx_upload
    /** `warning` — ui. */
    val Warning: Int get() = R.drawable.ic_gx_warning

    /** Every icon, grouped by family. */
    val all: List<GxIcon> = listOf(
        GxIcon("airbrush", R.drawable.ic_gx_airbrush, GxIconCategory.TOOLS, listOf("spray", "atomiser", "soft", "mist")),
        GxIcon("alpha-lock", R.drawable.ic_gx_alpha_lock, GxIconCategory.TOOLS, listOf("lock transparency", "paint inside", "preserve")),
        GxIcon("blob-brush", R.drawable.ic_gx_blob_brush, GxIconCategory.TOOLS, listOf("merge shapes", "vector paint", "blob")),
        GxIcon("blur", R.drawable.ic_gx_blur, GxIconCategory.TOOLS, listOf("soften", "out of focus", "droplet")),
        GxIcon("brush", R.drawable.ic_gx_brush, GxIconCategory.TOOLS, listOf("paint", "bristle", "draw", "round brush")),
        GxIcon("brush-angle", R.drawable.ic_gx_brush_angle, GxIconCategory.TOOLS, listOf("rotation", "nib angle", "protractor")),
        GxIcon("brush-flow", R.drawable.ic_gx_brush_flow, GxIconCategory.TOOLS, listOf("rate", "load", "delivery")),
        GxIcon("brush-hardness", R.drawable.ic_gx_brush_hardness, GxIconCategory.TOOLS, listOf("edge", "falloff", "core")),
        GxIcon("brush-import", R.drawable.ic_gx_brush_import, GxIconCategory.TOOLS, listOf("load brush", "install", "abr")),
        GxIcon("brush-library", R.drawable.ic_gx_brush_library, GxIconCategory.TOOLS, listOf("brushes", "presets", "pot")),
        GxIcon("brush-opacity", R.drawable.ic_gx_brush_opacity, GxIconCategory.TOOLS, listOf("alpha", "coverage", "translucent")),
        GxIcon("brush-roundness", R.drawable.ic_gx_brush_roundness, GxIconCategory.TOOLS, listOf("flatten", "squash", "ellipse nib")),
        GxIcon("brush-scatter", R.drawable.ic_gx_brush_scatter, GxIconCategory.TOOLS, listOf("jitter", "spread", "random")),
        GxIcon("brush-settings", R.drawable.ic_gx_brush_settings, GxIconCategory.TOOLS, listOf("brush studio", "parameters", "engine")),
        GxIcon("brush-size", R.drawable.ic_gx_brush_size, GxIconCategory.TOOLS, listOf("diameter", "radius", "scale brush")),
        GxIcon("brush-spacing", R.drawable.ic_gx_brush_spacing, GxIconCategory.TOOLS, listOf("stamps", "interval", "gap")),
        GxIcon("brush-texture", R.drawable.ic_gx_brush_texture, GxIconCategory.TOOLS, listOf("grain", "tooth", "paper")),
        GxIcon("burn", R.drawable.ic_gx_burn, GxIconCategory.TOOLS, listOf("darken", "shade", "cupped hand", "aperture")),
        GxIcon("calligraphy", R.drawable.ic_gx_calligraphy, GxIconCategory.TOOLS, listOf("broad edge", "lettering", "italic nib")),
        GxIcon("chalk", R.drawable.ic_gx_chalk, GxIconCategory.TOOLS, listOf("pastel", "dry media", "stick")),
        GxIcon("charcoal", R.drawable.ic_gx_charcoal, GxIconCategory.TOOLS, listOf("carbon", "smudgy", "dry media")),
        GxIcon("colordrop", R.drawable.ic_gx_colordrop, GxIconCategory.TOOLS, listOf("flood fill", "drag colour", "drop")),
        GxIcon("crayon", R.drawable.ic_gx_crayon, GxIconCategory.TOOLS, listOf("wax", "kids", "stub")),
        GxIcon("dodge", R.drawable.ic_gx_dodge, GxIconCategory.TOOLS, listOf("lighten", "hold back", "darkroom")),
        GxIcon("eraser", R.drawable.ic_gx_eraser, GxIconCategory.TOOLS, listOf("rub out", "delete", "undo mark")),
        GxIcon("eraser-hard", R.drawable.ic_gx_eraser_hard, GxIconCategory.TOOLS, listOf("hard edge", "crisp", "block")),
        GxIcon("eraser-soft", R.drawable.ic_gx_eraser_soft, GxIconCategory.TOOLS, listOf("feather", "soft edge", "fade")),
        GxIcon("eyedropper", R.drawable.ic_gx_eyedropper, GxIconCategory.TOOLS, listOf("picker", "sample", "colour pick")),
        GxIcon("fill", R.drawable.ic_gx_fill, GxIconCategory.TOOLS, listOf("paint bucket", "flood", "pour")),
        GxIcon("guide-drawing", R.drawable.ic_gx_guide_drawing, GxIconCategory.TOOLS, listOf("assist", "grid guide", "on rails")),
        GxIcon("guide-isometric", R.drawable.ic_gx_guide_isometric, GxIconCategory.TOOLS, listOf("axonometric", "30 degrees", "isometric")),
        GxIcon("guide-perspective", R.drawable.ic_gx_guide_perspective, GxIconCategory.TOOLS, listOf("vanishing point", "one point", "recede")),
        GxIcon("heal", R.drawable.ic_gx_heal, GxIconCategory.TOOLS, listOf("healing brush", "plaster", "repair")),
        GxIcon("heal-spot", R.drawable.ic_gx_heal_spot, GxIconCategory.TOOLS, listOf("blemish", "spot removal", "target")),
        GxIcon("liquify", R.drawable.ic_gx_liquify, GxIconCategory.TOOLS, listOf("warp", "push pixels", "swirl")),
        GxIcon("marker", R.drawable.ic_gx_marker, GxIconCategory.TOOLS, listOf("felt tip", "chisel", "highlighter")),
        GxIcon("mixer-brush", R.drawable.ic_gx_mixer_brush, GxIconCategory.TOOLS, listOf("wet mix", "blend paint", "load")),
        GxIcon("oil-brush", R.drawable.ic_gx_oil_brush, GxIconCategory.TOOLS, listOf("flat brush", "bristle", "impasto")),
        GxIcon("patch", R.drawable.ic_gx_patch, GxIconCategory.TOOLS, listOf("region repair", "graft", "swap")),
        GxIcon("pen-ink", R.drawable.ic_gx_pen_ink, GxIconCategory.TOOLS, listOf("nib", "dip pen", "ink", "line art")),
        GxIcon("pencil", R.drawable.ic_gx_pencil, GxIconCategory.TOOLS, listOf("draw", "sketch", "graphite", "edit")),
        GxIcon("pressure", R.drawable.ic_gx_pressure, GxIconCategory.TOOLS, listOf("force", "hard press", "weight")),
        GxIcon("quickshape", R.drawable.ic_gx_quickshape, GxIconCategory.TOOLS, listOf("snap to shape", "clean up", "auto shape")),
        GxIcon("red-eye", R.drawable.ic_gx_red_eye, GxIconCategory.TOOLS, listOf("pupil", "flash", "portrait fix")),
        GxIcon("roller", R.drawable.ic_gx_roller, GxIconCategory.TOOLS, listOf("paint roller", "flat fill", "coat")),
        GxIcon("sharpen", R.drawable.ic_gx_sharpen, GxIconCategory.TOOLS, listOf("crisp", "detail", "cone")),
        GxIcon("smudge", R.drawable.ic_gx_smudge, GxIconCategory.TOOLS, listOf("finger", "drag", "blend")),
        GxIcon("sponge", R.drawable.ic_gx_sponge, GxIconCategory.TOOLS, listOf("saturation", "soak", "porous")),
        GxIcon("spray-can", R.drawable.ic_gx_spray_can, GxIconCategory.TOOLS, listOf("aerosol", "graffiti", "rattle can")),
        GxIcon("stamp", R.drawable.ic_gx_stamp, GxIconCategory.TOOLS, listOf("clone", "rubber stamp", "duplicate source")),
        GxIcon("stamp-pattern", R.drawable.ic_gx_stamp_pattern, GxIconCategory.TOOLS, listOf("pattern stamp", "tile", "repeat")),
        GxIcon("streamline", R.drawable.ic_gx_streamline, GxIconCategory.TOOLS, listOf("stabiliser", "smoothing", "steady")),
        GxIcon("stylus", R.drawable.ic_gx_stylus, GxIconCategory.TOOLS, listOf("pen hardware", "pencil", "digitiser")),
        GxIcon("symmetry", R.drawable.ic_gx_symmetry, GxIconCategory.TOOLS, listOf("mirror", "reflect drawing", "guide")),
        GxIcon("symmetry-horizontal", R.drawable.ic_gx_symmetry_horizontal, GxIconCategory.TOOLS, listOf("mirror y", "top bottom")),
        GxIcon("symmetry-quadrant", R.drawable.ic_gx_symmetry_quadrant, GxIconCategory.TOOLS, listOf("four way", "kaleidoscope")),
        GxIcon("symmetry-radial", R.drawable.ic_gx_symmetry_radial, GxIconCategory.TOOLS, listOf("rotational", "mandala", "spokes")),
        GxIcon("symmetry-vertical", R.drawable.ic_gx_symmetry_vertical, GxIconCategory.TOOLS, listOf("mirror x", "left right")),
        GxIcon("tilt", R.drawable.ic_gx_tilt, GxIconCategory.TOOLS, listOf("angle", "shading", "lean")),
        GxIcon("watercolor", R.drawable.ic_gx_watercolor, GxIconCategory.TOOLS, listOf("wet", "wash", "bleed")),
        GxIcon("mask", R.drawable.ic_gx_mask, GxIconCategory.SELECTION, listOf("layer mask", "reveal", "conceal")),
        GxIcon("mask-add", R.drawable.ic_gx_mask_add, GxIconCategory.SELECTION, listOf("new mask", "attach mask")),
        GxIcon("mask-apply", R.drawable.ic_gx_mask_apply, GxIconCategory.SELECTION, listOf("bake mask", "commit", "flatten mask")),
        GxIcon("mask-channel", R.drawable.ic_gx_mask_channel, GxIconCategory.SELECTION, listOf("save selection", "alpha channel", "store")),
        GxIcon("mask-clipping", R.drawable.ic_gx_mask_clipping, GxIconCategory.SELECTION, listOf("clip to layer", "clipped", "inside")),
        GxIcon("mask-delete", R.drawable.ic_gx_mask_delete, GxIconCategory.SELECTION, listOf("remove mask", "discard")),
        GxIcon("mask-disable", R.drawable.ic_gx_mask_disable, GxIconCategory.SELECTION, listOf("turn off mask", "bypass")),
        GxIcon("mask-luminance", R.drawable.ic_gx_mask_luminance, GxIconCategory.SELECTION, listOf("luminosity mask", "by tone", "highlights")),
        GxIcon("mask-quick", R.drawable.ic_gx_mask_quick, GxIconCategory.SELECTION, listOf("quick mask", "rubylith", "paint a selection")),
        GxIcon("mask-vector", R.drawable.ic_gx_mask_vector, GxIconCategory.SELECTION, listOf("path mask", "clip path")),
        GxIcon("select-add", R.drawable.ic_gx_select_add, GxIconCategory.SELECTION, listOf("union", "unite", "add to selection")),
        GxIcon("select-all", R.drawable.ic_gx_select_all, GxIconCategory.SELECTION, listOf("everything", "whole canvas")),
        GxIcon("select-color-range", R.drawable.ic_gx_select_color_range, GxIconCategory.SELECTION, listOf("by colour", "tolerance", "sample")),
        GxIcon("select-ellipse", R.drawable.ic_gx_select_ellipse, GxIconCategory.SELECTION, listOf("marquee", "oval", "round")),
        GxIcon("select-exclude", R.drawable.ic_gx_select_exclude, GxIconCategory.SELECTION, listOf("difference", "xor", "either but not both")),
        GxIcon("select-feather", R.drawable.ic_gx_select_feather, GxIconCategory.SELECTION, listOf("soften edge", "falloff", "blur selection")),
        GxIcon("select-focus", R.drawable.ic_gx_select_focus, GxIconCategory.SELECTION, listOf("focus area", "depth", "sharp region")),
        GxIcon("select-grow", R.drawable.ic_gx_select_grow, GxIconCategory.SELECTION, listOf("expand", "dilate", "outward")),
        GxIcon("select-intersect", R.drawable.ic_gx_select_intersect, GxIconCategory.SELECTION, listOf("overlap", "common", "both")),
        GxIcon("select-invert", R.drawable.ic_gx_select_invert, GxIconCategory.SELECTION, listOf("inverse", "everything else", "swap")),
        GxIcon("select-lasso", R.drawable.ic_gx_select_lasso, GxIconCategory.SELECTION, listOf("freehand", "draw selection", "loop")),
        GxIcon("select-magnetic", R.drawable.ic_gx_select_magnetic, GxIconCategory.SELECTION, listOf("snap to edge", "magnetic lasso", "cling")),
        GxIcon("select-none", R.drawable.ic_gx_select_none, GxIconCategory.SELECTION, listOf("deselect", "drop selection", "clear")),
        GxIcon("select-object", R.drawable.ic_gx_select_object, GxIconCategory.SELECTION, listOf("object select", "auto", "detect")),
        GxIcon("select-polygon", R.drawable.ic_gx_select_polygon, GxIconCategory.SELECTION, listOf("polygonal lasso", "straight", "vertices")),
        GxIcon("select-quick", R.drawable.ic_gx_select_quick, GxIconCategory.SELECTION, listOf("quick selection", "brush select", "grow")),
        GxIcon("select-rect", R.drawable.ic_gx_select_rect, GxIconCategory.SELECTION, listOf("marquee", "rectangle", "crop area")),
        GxIcon("select-refine", R.drawable.ic_gx_select_refine, GxIconCategory.SELECTION, listOf("refine edge", "hair", "detail")),
        GxIcon("select-reselect", R.drawable.ic_gx_select_reselect, GxIconCategory.SELECTION, listOf("restore selection", "again")),
        GxIcon("select-shrink", R.drawable.ic_gx_select_shrink, GxIconCategory.SELECTION, listOf("contract", "erode", "inward")),
        GxIcon("select-similar", R.drawable.ic_gx_select_similar, GxIconCategory.SELECTION, listOf("grow", "like this", "match")),
        GxIcon("select-sky", R.drawable.ic_gx_select_sky, GxIconCategory.SELECTION, listOf("sky replacement", "horizon", "upper region")),
        GxIcon("select-subject", R.drawable.ic_gx_select_subject, GxIconCategory.SELECTION, listOf("person", "cut out", "isolate")),
        GxIcon("select-subtract", R.drawable.ic_gx_select_subtract, GxIconCategory.SELECTION, listOf("minus front", "remove", "take away")),
        GxIcon("select-transform", R.drawable.ic_gx_select_transform, GxIconCategory.SELECTION, listOf("transform selection", "handles", "resize")),
        GxIcon("select-wand", R.drawable.ic_gx_select_wand, GxIconCategory.SELECTION, listOf("magic wand", "similar pixels", "tolerance")),
        GxIcon("artboard", R.drawable.ic_gx_artboard, GxIconCategory.LAYERS, listOf("canvas", "page", "document frame")),
        GxIcon("artboard-add", R.drawable.ic_gx_artboard_add, GxIconCategory.LAYERS, listOf("new artboard", "new page")),
        GxIcon("layer-add", R.drawable.ic_gx_layer_add, GxIconCategory.LAYERS, listOf("new layer", "plus")),
        GxIcon("layer-adjustment", R.drawable.ic_gx_layer_adjustment, GxIconCategory.LAYERS, listOf("adjustment layer", "non destructive")),
        GxIcon("layer-background", R.drawable.ic_gx_layer_background, GxIconCategory.LAYERS, listOf("backdrop", "base", "foundation")),
        GxIcon("layer-blend", R.drawable.ic_gx_layer_blend, GxIconCategory.LAYERS, listOf("blend mode", "mix", "interaction")),
        GxIcon("layer-count", R.drawable.ic_gx_layer_count, GxIconCategory.LAYERS, listOf("how many", "stack depth")),
        GxIcon("layer-delete", R.drawable.ic_gx_layer_delete, GxIconCategory.LAYERS, listOf("remove layer", "discard")),
        GxIcon("layer-duplicate", R.drawable.ic_gx_layer_duplicate, GxIconCategory.LAYERS, listOf("copy layer", "clone layer")),
        GxIcon("layer-fill", R.drawable.ic_gx_layer_fill, GxIconCategory.LAYERS, listOf("solid colour", "fill layer")),
        GxIcon("layer-filter", R.drawable.ic_gx_layer_filter, GxIconCategory.LAYERS, listOf("find layer", "search stack")),
        GxIcon("layer-flatten", R.drawable.ic_gx_layer_flatten, GxIconCategory.LAYERS, listOf("one layer", "collapse all")),
        GxIcon("layer-frame", R.drawable.ic_gx_layer_frame, GxIconCategory.LAYERS, listOf("frame tool", "placeholder", "crop into")),
        GxIcon("layer-group", R.drawable.ic_gx_layer_group, GxIconCategory.LAYERS, listOf("folder", "nest", "group")),
        GxIcon("layer-hidden", R.drawable.ic_gx_layer_hidden, GxIconCategory.LAYERS, listOf("hide", "eye off", "invisible")),
        GxIcon("layer-isolate", R.drawable.ic_gx_layer_isolate, GxIconCategory.LAYERS, listOf("solo", "only this", "focus layer")),
        GxIcon("layer-link", R.drawable.ic_gx_layer_link, GxIconCategory.LAYERS, listOf("chain", "tie together", "move as one")),
        GxIcon("layer-lock", R.drawable.ic_gx_layer_lock, GxIconCategory.LAYERS, listOf("protect", "padlock", "read only")),
        GxIcon("layer-lower", R.drawable.ic_gx_layer_lower, GxIconCategory.LAYERS, listOf("send backward", "down one")),
        GxIcon("layer-merge-down", R.drawable.ic_gx_layer_merge_down, GxIconCategory.LAYERS, listOf("combine", "flatten two", "down")),
        GxIcon("layer-merge-visible", R.drawable.ic_gx_layer_merge_visible, GxIconCategory.LAYERS, listOf("merge shown", "collapse visible")),
        GxIcon("layer-opacity", R.drawable.ic_gx_layer_opacity, GxIconCategory.LAYERS, listOf("transparency", "alpha", "fade")),
        GxIcon("layer-raise", R.drawable.ic_gx_layer_raise, GxIconCategory.LAYERS, listOf("bring forward", "up one")),
        GxIcon("layer-rasterize", R.drawable.ic_gx_layer_rasterize, GxIconCategory.LAYERS, listOf("to pixels", "commit", "bake")),
        GxIcon("layer-reference", R.drawable.ic_gx_layer_reference, GxIconCategory.LAYERS, listOf("reference layer", "source", "pin")),
        GxIcon("layer-rename", R.drawable.ic_gx_layer_rename, GxIconCategory.LAYERS, listOf("label", "title", "edit name")),
        GxIcon("layer-smart", R.drawable.ic_gx_layer_smart, GxIconCategory.LAYERS, listOf("smart object", "linked", "non destructive")),
        GxIcon("layer-style", R.drawable.ic_gx_layer_style, GxIconCategory.LAYERS, listOf("fx", "effects", "layer effects")),
        GxIcon("layer-tag", R.drawable.ic_gx_layer_tag, GxIconCategory.LAYERS, listOf("colour label", "flag", "sort")),
        GxIcon("layer-thumbnail", R.drawable.ic_gx_layer_thumbnail, GxIconCategory.LAYERS, listOf("preview", "row", "panel row")),
        GxIcon("layer-to-back", R.drawable.ic_gx_layer_to_back, GxIconCategory.LAYERS, listOf("send to back", "bottom")),
        GxIcon("layer-to-front", R.drawable.ic_gx_layer_to_front, GxIconCategory.LAYERS, listOf("bring to front", "top")),
        GxIcon("layer-ungroup", R.drawable.ic_gx_layer_ungroup, GxIconCategory.LAYERS, listOf("release", "unnest", "flatten group")),
        GxIcon("layer-unlink", R.drawable.ic_gx_layer_unlink, GxIconCategory.LAYERS, listOf("break chain", "release")),
        GxIcon("layer-unlock", R.drawable.ic_gx_layer_unlock, GxIconCategory.LAYERS, listOf("unprotect", "open lock", "editable")),
        GxIcon("layer-visible", R.drawable.ic_gx_layer_visible, GxIconCategory.LAYERS, listOf("show", "eye", "toggle")),
        GxIcon("layers", R.drawable.ic_gx_layers, GxIconCategory.LAYERS, listOf("stack", "sheets", "panel")),
        GxIcon("auto-tone", R.drawable.ic_gx_auto_tone, GxIconCategory.COLOR, listOf("auto levels", "fix", "one tap")),
        GxIcon("black-white", R.drawable.ic_gx_black_white, GxIconCategory.COLOR, listOf("mono", "channel mix to grey")),
        GxIcon("brightness", R.drawable.ic_gx_brightness, GxIconCategory.COLOR, listOf("light", "sun", "lighten")),
        GxIcon("channel-mixer", R.drawable.ic_gx_channel_mixer, GxIconCategory.COLOR, listOf("per channel", "recombine")),
        GxIcon("clarity", R.drawable.ic_gx_clarity, GxIconCategory.COLOR, listOf("local contrast", "punch", "dehaze")),
        GxIcon("color-alpha", R.drawable.ic_gx_color_alpha, GxIconCategory.COLOR, listOf("transparency", "opacity channel")),
        GxIcon("color-balance", R.drawable.ic_gx_color_balance, GxIconCategory.COLOR, listOf("cast", "cool warm", "scales")),
        GxIcon("color-cmyk", R.drawable.ic_gx_color_cmyk, GxIconCategory.COLOR, listOf("subtractive", "print", "process")),
        GxIcon("color-disc", R.drawable.ic_gx_color_disc, GxIconCategory.COLOR, listOf("picker", "wheel", "choose colour")),
        GxIcon("color-harmony", R.drawable.ic_gx_color_harmony, GxIconCategory.COLOR, listOf("complementary", "triad", "scheme")),
        GxIcon("color-hex", R.drawable.ic_gx_color_hex, GxIconCategory.COLOR, listOf("code", "value", "exact")),
        GxIcon("color-history", R.drawable.ic_gx_color_history, GxIconCategory.COLOR, listOf("recent", "used", "last colours")),
        GxIcon("color-lookup", R.drawable.ic_gx_color_lookup, GxIconCategory.COLOR, listOf("lut", "preset grade", "cube")),
        GxIcon("color-profile", R.drawable.ic_gx_color_profile, GxIconCategory.COLOR, listOf("gamut", "icc", "colour space")),
        GxIcon("color-rgb", R.drawable.ic_gx_color_rgb, GxIconCategory.COLOR, listOf("additive", "screen", "channels")),
        GxIcon("color-swatch", R.drawable.ic_gx_color_swatch, GxIconCategory.COLOR, listOf("chip", "sample", "current colour")),
        GxIcon("color-swatches", R.drawable.ic_gx_color_swatches, GxIconCategory.COLOR, listOf("palette", "library", "saved colours")),
        GxIcon("contrast", R.drawable.ic_gx_contrast, GxIconCategory.COLOR, listOf("tonal range", "hard soft")),
        GxIcon("curves", R.drawable.ic_gx_curves, GxIconCategory.COLOR, listOf("tone curve", "s curve", "remap")),
        GxIcon("desaturate", R.drawable.ic_gx_desaturate, GxIconCategory.COLOR, listOf("greyscale", "remove colour")),
        GxIcon("exposure", R.drawable.ic_gx_exposure, GxIconCategory.COLOR, listOf("stops", "aperture", "iris")),
        GxIcon("gradient", R.drawable.ic_gx_gradient, GxIconCategory.COLOR, listOf("ramp", "blend", "fade")),
        GxIcon("gradient-angle", R.drawable.ic_gx_gradient_angle, GxIconCategory.COLOR, listOf("sweep", "conical")),
        GxIcon("gradient-linear", R.drawable.ic_gx_gradient_linear, GxIconCategory.COLOR, listOf("axis ramp", "straight")),
        GxIcon("gradient-map", R.drawable.ic_gx_gradient_map, GxIconCategory.COLOR, listOf("remap tone to colour", "duotone")),
        GxIcon("gradient-mesh", R.drawable.ic_gx_gradient_mesh, GxIconCategory.COLOR, listOf("mesh", "surface", "multi point")),
        GxIcon("gradient-radial", R.drawable.ic_gx_gradient_radial, GxIconCategory.COLOR, listOf("from centre", "round ramp")),
        GxIcon("grain", R.drawable.ic_gx_grain, GxIconCategory.COLOR, listOf("noise", "film", "texture")),
        GxIcon("histogram", R.drawable.ic_gx_histogram, GxIconCategory.COLOR, listOf("distribution", "readout", "levels display")),
        GxIcon("hue", R.drawable.ic_gx_hue, GxIconCategory.COLOR, listOf("colour angle", "shift hue", "wheel")),
        GxIcon("invert", R.drawable.ic_gx_invert, GxIconCategory.COLOR, listOf("negative", "flip tone")),
        GxIcon("levels", R.drawable.ic_gx_levels, GxIconCategory.COLOR, listOf("histogram", "black point", "white point")),
        GxIcon("photo-filter", R.drawable.ic_gx_photo_filter, GxIconCategory.COLOR, listOf("warming filter", "gel", "lens filter")),
        GxIcon("posterize", R.drawable.ic_gx_posterize, GxIconCategory.COLOR, listOf("quantise", "steps", "bands")),
        GxIcon("replace-color", R.drawable.ic_gx_replace_color, GxIconCategory.COLOR, listOf("swap hue", "recolour")),
        GxIcon("saturation", R.drawable.ic_gx_saturation, GxIconCategory.COLOR, listOf("intensity", "chroma", "vivid")),
        GxIcon("selective-color", R.drawable.ic_gx_selective_color, GxIconCategory.COLOR, listOf("one hue only", "target colour")),
        GxIcon("shadows-highlights", R.drawable.ic_gx_shadows_highlights, GxIconCategory.COLOR, listOf("recover", "lift shadows", "pull highlights")),
        GxIcon("temperature", R.drawable.ic_gx_temperature, GxIconCategory.COLOR, listOf("warm cool", "kelvin", "white balance")),
        GxIcon("threshold", R.drawable.ic_gx_threshold, GxIconCategory.COLOR, listOf("cutoff", "two tone", "clip")),
        GxIcon("tint", R.drawable.ic_gx_tint, GxIconCategory.COLOR, listOf("cast", "shift", "green magenta")),
        GxIcon("vibrance", R.drawable.ic_gx_vibrance, GxIconCategory.COLOR, listOf("smart saturation", "protect skin")),
        GxIcon("vignette", R.drawable.ic_gx_vignette, GxIconCategory.COLOR, listOf("edge darkening", "corners")),
        GxIcon("filter-bevel", R.drawable.ic_gx_filter_bevel, GxIconCategory.FILTERS, listOf("ridge", "3d edge", "chamfer")),
        GxIcon("filter-blur-gaussian", R.drawable.ic_gx_filter_blur_gaussian, GxIconCategory.FILTERS, listOf("soft focus", "smooth")),
        GxIcon("filter-blur-lens", R.drawable.ic_gx_filter_blur_lens, GxIconCategory.FILTERS, listOf("depth of field", "bokeh")),
        GxIcon("filter-blur-motion", R.drawable.ic_gx_filter_blur_motion, GxIconCategory.FILTERS, listOf("speed", "streak", "movement")),
        GxIcon("filter-blur-radial", R.drawable.ic_gx_filter_blur_radial, GxIconCategory.FILTERS, listOf("zoom blur", "spin blur")),
        GxIcon("filter-clone-source", R.drawable.ic_gx_filter_clone_source, GxIconCategory.FILTERS, listOf("sample point", "reference")),
        GxIcon("filter-content-aware-fill", R.drawable.ic_gx_filter_content_aware_fill, GxIconCategory.FILTERS, listOf("ai fill", "remove and fill")),
        GxIcon("filter-crystallize", R.drawable.ic_gx_filter_crystallize, GxIconCategory.FILTERS, listOf("facets", "voronoi")),
        GxIcon("filter-distort-pinch", R.drawable.ic_gx_filter_distort_pinch, GxIconCategory.FILTERS, listOf("squeeze", "implode")),
        GxIcon("filter-distort-spherize", R.drawable.ic_gx_filter_distort_spherize, GxIconCategory.FILTERS, listOf("bulge", "inflate", "fisheye")),
        GxIcon("filter-distort-twirl", R.drawable.ic_gx_filter_distort_twirl, GxIconCategory.FILTERS, listOf("swirl", "vortex")),
        GxIcon("filter-distort-wave", R.drawable.ic_gx_filter_distort_wave, GxIconCategory.FILTERS, listOf("ripple", "undulate")),
        GxIcon("filter-emboss", R.drawable.ic_gx_filter_emboss, GxIconCategory.FILTERS, listOf("relief", "3d edge")),
        GxIcon("filter-gallery", R.drawable.ic_gx_filter_gallery, GxIconCategory.FILTERS, listOf("stack of filters", "fx library")),
        GxIcon("filter-generative-fill", R.drawable.ic_gx_filter_generative_fill, GxIconCategory.FILTERS, listOf("ai generate", "text to image fill")),
        GxIcon("filter-glow", R.drawable.ic_gx_filter_glow, GxIconCategory.FILTERS, listOf("outer glow", "bloom")),
        GxIcon("filter-halftone", R.drawable.ic_gx_filter_halftone, GxIconCategory.FILTERS, listOf("dots", "print screen", "ben-day")),
        GxIcon("filter-lens-flare", R.drawable.ic_gx_filter_lens_flare, GxIconCategory.FILTERS, listOf("light leak", "sun flare")),
        GxIcon("filter-liquify", R.drawable.ic_gx_filter_liquify, GxIconCategory.FILTERS, listOf("push", "warp", "reshape")),
        GxIcon("filter-mosaic", R.drawable.ic_gx_filter_mosaic, GxIconCategory.FILTERS, listOf("pixelate", "blocks")),
        GxIcon("filter-noise-add", R.drawable.ic_gx_filter_noise_add, GxIconCategory.FILTERS, listOf("grain", "static", "speckle")),
        GxIcon("filter-noise-reduce", R.drawable.ic_gx_filter_noise_reduce, GxIconCategory.FILTERS, listOf("denoise", "clean up", "smooth grain")),
        GxIcon("filter-render-clouds", R.drawable.ic_gx_filter_render_clouds, GxIconCategory.FILTERS, listOf("procedural sky", "fractal")),
        GxIcon("filter-shadow-drop", R.drawable.ic_gx_filter_shadow_drop, GxIconCategory.FILTERS, listOf("cast shadow", "depth")),
        GxIcon("filter-shadow-inner", R.drawable.ic_gx_filter_shadow_inner, GxIconCategory.FILTERS, listOf("inset shadow", "recessed")),
        GxIcon("filter-sharpen-unsharp", R.drawable.ic_gx_filter_sharpen_unsharp, GxIconCategory.FILTERS, listOf("edge contrast", "unsharp mask")),
        GxIcon("filter-sky-replace", R.drawable.ic_gx_filter_sky_replace, GxIconCategory.FILTERS, listOf("ai sky", "replace background")),
        GxIcon("filter-smart-radius", R.drawable.ic_gx_filter_smart_radius, GxIconCategory.FILTERS, listOf("adaptive edge", "AI mask edge")),
        GxIcon("filter-stroke-outline", R.drawable.ic_gx_filter_stroke_outline, GxIconCategory.FILTERS, listOf("outline effect", "border")),
        GxIcon("filter-vanishing-point", R.drawable.ic_gx_filter_vanishing_point, GxIconCategory.FILTERS, listOf("perspective clone", "3d plane")),
        GxIcon("filter-vignette-post", R.drawable.ic_gx_filter_vignette_post, GxIconCategory.FILTERS, listOf("darken corners", "frame edge")),
        GxIcon("anchor-convert", R.drawable.ic_gx_anchor_convert, GxIconCategory.VECTOR, listOf("corner smooth toggle", "convert point")),
        GxIcon("boolean-exclude", R.drawable.ic_gx_boolean_exclude, GxIconCategory.VECTOR, listOf("pathfinder exclude")),
        GxIcon("boolean-intersect", R.drawable.ic_gx_boolean_intersect, GxIconCategory.VECTOR, listOf("pathfinder intersect")),
        GxIcon("boolean-minus", R.drawable.ic_gx_boolean_minus, GxIconCategory.VECTOR, listOf("pathfinder subtract", "minus front")),
        GxIcon("boolean-unite", R.drawable.ic_gx_boolean_unite, GxIconCategory.VECTOR, listOf("pathfinder add", "merge shapes")),
        GxIcon("clipping-mask-vector", R.drawable.ic_gx_clipping_mask_vector, GxIconCategory.VECTOR, listOf("crop to shape", "clip path")),
        GxIcon("compound-path", R.drawable.ic_gx_compound_path, GxIconCategory.VECTOR, listOf("make compound", "holes")),
        GxIcon("guide-ruler", R.drawable.ic_gx_guide_ruler, GxIconCategory.VECTOR, listOf("smart guide", "snap")),
        GxIcon("handle-asymmetric", R.drawable.ic_gx_handle_asymmetric, GxIconCategory.VECTOR, listOf("broken handles", "independent tangent")),
        GxIcon("handle-symmetric", R.drawable.ic_gx_handle_symmetric, GxIconCategory.VECTOR, listOf("smooth handles", "mirrored tangent")),
        GxIcon("path-close", R.drawable.ic_gx_path_close, GxIconCategory.VECTOR, listOf("closed path", "join ends")),
        GxIcon("path-eraser-vector", R.drawable.ic_gx_path_eraser_vector, GxIconCategory.VECTOR, listOf("vector eraser", "erase path")),
        GxIcon("path-knife", R.drawable.ic_gx_path_knife, GxIconCategory.VECTOR, listOf("cut shape", "slice")),
        GxIcon("path-offset", R.drawable.ic_gx_path_offset, GxIconCategory.VECTOR, listOf("parallel copy", "grow path")),
        GxIcon("path-open", R.drawable.ic_gx_path_open, GxIconCategory.VECTOR, listOf("cut path", "scissors")),
        GxIcon("path-outline-stroke", R.drawable.ic_gx_path_outline_stroke, GxIconCategory.VECTOR, listOf("stroke to fill", "expand stroke")),
        GxIcon("path-reverse", R.drawable.ic_gx_path_reverse, GxIconCategory.VECTOR, listOf("flip direction", "winding")),
        GxIcon("path-select-direct", R.drawable.ic_gx_path_select_direct, GxIconCategory.VECTOR, listOf("white arrow", "edit anchors")),
        GxIcon("path-select-group", R.drawable.ic_gx_path_select_group, GxIconCategory.VECTOR, listOf("black arrow", "select object")),
        GxIcon("path-simplify", R.drawable.ic_gx_path_simplify, GxIconCategory.VECTOR, listOf("reduce points", "clean path")),
        GxIcon("path-width", R.drawable.ic_gx_path_width, GxIconCategory.VECTOR, listOf("variable width", "width profile")),
        GxIcon("pen", R.drawable.ic_gx_pen, GxIconCategory.VECTOR, listOf("bezier", "path tool", "draw vector")),
        GxIcon("pen-add", R.drawable.ic_gx_pen_add, GxIconCategory.VECTOR, listOf("add anchor", "insert point")),
        GxIcon("pen-remove", R.drawable.ic_gx_pen_remove, GxIconCategory.VECTOR, listOf("delete anchor", "remove point")),
        GxIcon("shape-line", R.drawable.ic_gx_shape_line, GxIconCategory.VECTOR, listOf("straight segment", "line tool")),
        GxIcon("shape-polygon", R.drawable.ic_gx_shape_polygon, GxIconCategory.VECTOR, listOf("vector polygon", "n sides")),
        GxIcon("shape-rectangle", R.drawable.ic_gx_shape_rectangle, GxIconCategory.VECTOR, listOf("vector rect", "live shape")),
        GxIcon("shape-spiral", R.drawable.ic_gx_shape_spiral, GxIconCategory.VECTOR, listOf("vector spiral", "coil")),
        GxIcon("shape-star", R.drawable.ic_gx_shape_star, GxIconCategory.VECTOR, listOf("vector star", "points")),
        GxIcon("trace-image", R.drawable.ic_gx_trace_image, GxIconCategory.VECTOR, listOf("image trace", "raster to vector")),
        GxIcon("vectorize", R.drawable.ic_gx_vectorize, GxIconCategory.VECTOR, listOf("auto vector", "convert to path")),
        GxIcon("baseline-shift", R.drawable.ic_gx_baseline_shift, GxIconCategory.TYPE, listOf("raise lower glyph")),
        GxIcon("find-replace-text", R.drawable.ic_gx_find_replace_text, GxIconCategory.TYPE, listOf("search text", "swap words")),
        GxIcon("font-family", R.drawable.ic_gx_font_family, GxIconCategory.TYPE, listOf("typeface", "font picker")),
        GxIcon("font-size", R.drawable.ic_gx_font_size, GxIconCategory.TYPE, listOf("point size", "text scale")),
        GxIcon("font-weight", R.drawable.ic_gx_font_weight, GxIconCategory.TYPE, listOf("bold", "font weight axis")),
        GxIcon("glyphs-panel", R.drawable.ic_gx_glyphs_panel, GxIconCategory.TYPE, listOf("special characters", "ligatures")),
        GxIcon("kerning", R.drawable.ic_gx_kerning, GxIconCategory.TYPE, listOf("letter spacing pair", "AV")),
        GxIcon("leading", R.drawable.ic_gx_leading, GxIconCategory.TYPE, listOf("line spacing", "row gap")),
        GxIcon("paragraph-align-center", R.drawable.ic_gx_paragraph_align_center, GxIconCategory.TYPE, listOf("centre text")),
        GxIcon("paragraph-align-left", R.drawable.ic_gx_paragraph_align_left, GxIconCategory.TYPE, listOf("justify left")),
        GxIcon("paragraph-align-right", R.drawable.ic_gx_paragraph_align_right, GxIconCategory.TYPE, listOf("justify right")),
        GxIcon("paragraph-indent", R.drawable.ic_gx_paragraph_indent, GxIconCategory.TYPE, listOf("first line indent")),
        GxIcon("paragraph-justify", R.drawable.ic_gx_paragraph_justify, GxIconCategory.TYPE, listOf("full justify")),
        GxIcon("spell-check", R.drawable.ic_gx_spell_check, GxIconCategory.TYPE, listOf("proofing", "typo underline")),
        GxIcon("text-color", R.drawable.ic_gx_text_color, GxIconCategory.TYPE, listOf("font colour", "fill text")),
        GxIcon("text-outline-convert", R.drawable.ic_gx_text_outline_convert, GxIconCategory.TYPE, listOf("create outlines", "text to shape")),
        GxIcon("tracking", R.drawable.ic_gx_tracking, GxIconCategory.TYPE, listOf("letter spacing all", "expand")),
        GxIcon("type", R.drawable.ic_gx_type, GxIconCategory.TYPE, listOf("text tool", "add text")),
        GxIcon("type-allcaps", R.drawable.ic_gx_type_allcaps, GxIconCategory.TYPE, listOf("uppercase", "caps lock")),
        GxIcon("type-area", R.drawable.ic_gx_type_area, GxIconCategory.TYPE, listOf("area text", "text in shape")),
        GxIcon("type-bold", R.drawable.ic_gx_type_bold, GxIconCategory.TYPE, listOf("strong", "b")),
        GxIcon("type-italic", R.drawable.ic_gx_type_italic, GxIconCategory.TYPE, listOf("oblique", "i")),
        GxIcon("type-mask", R.drawable.ic_gx_type_mask, GxIconCategory.TYPE, listOf("type selection", "text as selection")),
        GxIcon("type-path", R.drawable.ic_gx_type_path, GxIconCategory.TYPE, listOf("text on path", "curved type")),
        GxIcon("type-point", R.drawable.ic_gx_type_point, GxIconCategory.TYPE, listOf("point text", "click to type")),
        GxIcon("type-strikethrough", R.drawable.ic_gx_type_strikethrough, GxIconCategory.TYPE, listOf("s", "strike")),
        GxIcon("type-subscript", R.drawable.ic_gx_type_subscript, GxIconCategory.TYPE, listOf("index", "lowered")),
        GxIcon("type-superscript", R.drawable.ic_gx_type_superscript, GxIconCategory.TYPE, listOf("exponent", "raised")),
        GxIcon("type-underline", R.drawable.ic_gx_type_underline, GxIconCategory.TYPE, listOf("u")),
        GxIcon("type-vertical", R.drawable.ic_gx_type_vertical, GxIconCategory.TYPE, listOf("vertical text", "top to bottom")),
        GxIcon("type-warp", R.drawable.ic_gx_type_warp, GxIconCategory.TYPE, listOf("distort text", "arc text")),
        GxIcon("align-bottom", R.drawable.ic_gx_align_bottom, GxIconCategory.TRANSFORM, listOf("align objects bottom")),
        GxIcon("align-center-h", R.drawable.ic_gx_align_center_h, GxIconCategory.TRANSFORM, listOf("align objects centre horizontal")),
        GxIcon("align-left", R.drawable.ic_gx_align_left, GxIconCategory.TRANSFORM, listOf("align objects left")),
        GxIcon("align-middle-v", R.drawable.ic_gx_align_middle_v, GxIconCategory.TRANSFORM, listOf("align objects centre vertical")),
        GxIcon("align-right", R.drawable.ic_gx_align_right, GxIconCategory.TRANSFORM, listOf("align objects right")),
        GxIcon("align-to-artboard", R.drawable.ic_gx_align_to_artboard, GxIconCategory.TRANSFORM, listOf("align to canvas", "align to page")),
        GxIcon("align-top", R.drawable.ic_gx_align_top, GxIconCategory.TRANSFORM, listOf("align objects top")),
        GxIcon("distort", R.drawable.ic_gx_distort, GxIconCategory.TRANSFORM, listOf("free distort", "perspective corners")),
        GxIcon("distribute-horizontal", R.drawable.ic_gx_distribute_horizontal, GxIconCategory.TRANSFORM, listOf("equal gaps across")),
        GxIcon("distribute-vertical", R.drawable.ic_gx_distribute_vertical, GxIconCategory.TRANSFORM, listOf("equal gaps down")),
        GxIcon("flip-horizontal", R.drawable.ic_gx_flip_horizontal, GxIconCategory.TRANSFORM, listOf("mirror x", "flip left right")),
        GxIcon("flip-vertical", R.drawable.ic_gx_flip_vertical, GxIconCategory.TRANSFORM, listOf("mirror y", "flip top bottom")),
        GxIcon("move", R.drawable.ic_gx_move, GxIconCategory.TRANSFORM, listOf("position", "pan object", "translate")),
        GxIcon("perspective-transform", R.drawable.ic_gx_perspective_transform, GxIconCategory.TRANSFORM, listOf("perspective corners linked")),
        GxIcon("puppet-warp", R.drawable.ic_gx_puppet_warp, GxIconCategory.TRANSFORM, listOf("mesh warp", "pin and bend")),
        GxIcon("reset-transform", R.drawable.ic_gx_reset_transform, GxIconCategory.TRANSFORM, listOf("clear transform", "original state")),
        GxIcon("rotate", R.drawable.ic_gx_rotate, GxIconCategory.TRANSFORM, listOf("turn", "spin object")),
        GxIcon("rotate-180", R.drawable.ic_gx_rotate_180, GxIconCategory.TRANSFORM, listOf("half turn")),
        GxIcon("rotate-90-ccw", R.drawable.ic_gx_rotate_90_ccw, GxIconCategory.TRANSFORM, listOf("quarter turn left")),
        GxIcon("rotate-90-cw", R.drawable.ic_gx_rotate_90_cw, GxIconCategory.TRANSFORM, listOf("quarter turn right")),
        GxIcon("scale", R.drawable.ic_gx_scale, GxIconCategory.TRANSFORM, listOf("resize", "free transform")),
        GxIcon("scale-proportional", R.drawable.ic_gx_scale_proportional, GxIconCategory.TRANSFORM, listOf("lock aspect", "uniform scale")),
        GxIcon("skew", R.drawable.ic_gx_skew, GxIconCategory.TRANSFORM, listOf("shear", "slant")),
        GxIcon("smart-guides", R.drawable.ic_gx_smart_guides, GxIconCategory.TRANSFORM, listOf("alignment guides", "magenta lines")),
        GxIcon("snap-to-grid", R.drawable.ic_gx_snap_to_grid, GxIconCategory.TRANSFORM, listOf("snap", "grid magnet")),
        GxIcon("transform-again", R.drawable.ic_gx_transform_again, GxIconCategory.TRANSFORM, listOf("repeat transform")),
        GxIcon("bleed-marks", R.drawable.ic_gx_bleed_marks, GxIconCategory.DOCUMENT, listOf("print bleed", "trim marks")),
        GxIcon("canvas-size", R.drawable.ic_gx_canvas_size, GxIconCategory.DOCUMENT, listOf("resize canvas", "expand document")),
        GxIcon("crop", R.drawable.ic_gx_crop, GxIconCategory.DOCUMENT, listOf("trim", "crop tool")),
        GxIcon("crop-straighten", R.drawable.ic_gx_crop_straighten, GxIconCategory.DOCUMENT, listOf("level horizon", "de-skew")),
        GxIcon("document-close", R.drawable.ic_gx_document_close, GxIconCategory.DOCUMENT, listOf("close file")),
        GxIcon("document-new", R.drawable.ic_gx_document_new, GxIconCategory.DOCUMENT, listOf("new file", "blank canvas")),
        GxIcon("document-open", R.drawable.ic_gx_document_open, GxIconCategory.DOCUMENT, listOf("open file")),
        GxIcon("document-properties", R.drawable.ic_gx_document_properties, GxIconCategory.DOCUMENT, listOf("file info", "metadata")),
        GxIcon("document-revert", R.drawable.ic_gx_document_revert, GxIconCategory.DOCUMENT, listOf("revert to saved", "discard changes")),
        GxIcon("document-save", R.drawable.ic_gx_document_save, GxIconCategory.DOCUMENT, listOf("save file")),
        GxIcon("document-save-as", R.drawable.ic_gx_document_save_as, GxIconCategory.DOCUMENT, listOf("save copy", "duplicate file")),
        GxIcon("full-screen", R.drawable.ic_gx_full_screen, GxIconCategory.DOCUMENT, listOf("immersive mode", "hide panels")),
        GxIcon("grid-overlay", R.drawable.ic_gx_grid_overlay, GxIconCategory.DOCUMENT, listOf("pixel grid", "show grid")),
        GxIcon("guides", R.drawable.ic_gx_guides, GxIconCategory.DOCUMENT, listOf("ruler guides", "drag out guide")),
        GxIcon("image-size", R.drawable.ic_gx_image_size, GxIconCategory.DOCUMENT, listOf("resize image", "resample")),
        GxIcon("multi-window", R.drawable.ic_gx_multi_window, GxIconCategory.DOCUMENT, listOf("new window", "second view")),
        GxIcon("pan-hand", R.drawable.ic_gx_pan_hand, GxIconCategory.DOCUMENT, listOf("hand tool", "scroll canvas")),
        GxIcon("resample", R.drawable.ic_gx_resample, GxIconCategory.DOCUMENT, listOf("interpolation", "pixel resample")),
        GxIcon("rotate-view", R.drawable.ic_gx_rotate_view, GxIconCategory.DOCUMENT, listOf("rotate canvas view")),
        GxIcon("rulers", R.drawable.ic_gx_rulers, GxIconCategory.DOCUMENT, listOf("measurement guides", "show rulers")),
        GxIcon("split-view", R.drawable.ic_gx_split_view, GxIconCategory.DOCUMENT, listOf("compare", "before after")),
        GxIcon("thumbnails", R.drawable.ic_gx_thumbnails, GxIconCategory.DOCUMENT, listOf("gallery", "grid view")),
        GxIcon("view-actual-colors", R.drawable.ic_gx_view_actual_colors, GxIconCategory.DOCUMENT, listOf("proof colours", "soft proof")),
        GxIcon("view-cmyk-preview", R.drawable.ic_gx_view_cmyk_preview, GxIconCategory.DOCUMENT, listOf("gamut warning", "print preview")),
        GxIcon("zoom-100", R.drawable.ic_gx_zoom_100, GxIconCategory.DOCUMENT, listOf("actual size", "print size")),
        GxIcon("zoom-fit", R.drawable.ic_gx_zoom_fit, GxIconCategory.DOCUMENT, listOf("fit to screen", "fit window")),
        GxIcon("zoom-in", R.drawable.ic_gx_zoom_in, GxIconCategory.DOCUMENT, listOf("magnify", "increase view")),
        GxIcon("zoom-out", R.drawable.ic_gx_zoom_out, GxIconCategory.DOCUMENT, listOf("shrink", "decrease view")),
        GxIcon("action-play", R.drawable.ic_gx_action_play, GxIconCategory.HISTORY, listOf("run macro", "play action")),
        GxIcon("action-record", R.drawable.ic_gx_action_record, GxIconCategory.HISTORY, listOf("record macro", "start recording")),
        GxIcon("action-stop", R.drawable.ic_gx_action_stop, GxIconCategory.HISTORY, listOf("stop recording")),
        GxIcon("actions-panel", R.drawable.ic_gx_actions_panel, GxIconCategory.HISTORY, listOf("macro", "recorded steps")),
        GxIcon("batch-process", R.drawable.ic_gx_batch_process, GxIconCategory.HISTORY, listOf("run on folder", "bulk action")),
        GxIcon("checkpoint-restore", R.drawable.ic_gx_checkpoint_restore, GxIconCategory.HISTORY, listOf("roll back", "go to state")),
        GxIcon("clear-history", R.drawable.ic_gx_clear_history, GxIconCategory.HISTORY, listOf("purge undo stack", "forget states")),
        GxIcon("history-brush", R.drawable.ic_gx_history_brush, GxIconCategory.HISTORY, listOf("restore from history", "paint back")),
        GxIcon("history-panel", R.drawable.ic_gx_history_panel, GxIconCategory.HISTORY, listOf("state list", "undo stack")),
        GxIcon("history-snapshot", R.drawable.ic_gx_history_snapshot, GxIconCategory.HISTORY, listOf("checkpoint", "save state")),
        GxIcon("redo", R.drawable.ic_gx_redo, GxIconCategory.HISTORY, listOf("step forward", "ctrl y")),
        GxIcon("timer", R.drawable.ic_gx_timer, GxIconCategory.HISTORY, listOf("duration", "processing time")),
        GxIcon("undo", R.drawable.ic_gx_undo, GxIconCategory.HISTORY, listOf("step back", "ctrl z")),
        GxIcon("version-compare", R.drawable.ic_gx_version_compare, GxIconCategory.HISTORY, listOf("diff", "compare states")),
        GxIcon("export-gif", R.drawable.ic_gx_export_gif, GxIconCategory.ANIMATION, listOf("animated gif", "loop export")),
        GxIcon("export-video", R.drawable.ic_gx_export_video, GxIconCategory.ANIMATION, listOf("render animation", "save as video")),
        GxIcon("frame-add", R.drawable.ic_gx_frame_add, GxIconCategory.ANIMATION, listOf("new frame", "insert frame")),
        GxIcon("frame-delete", R.drawable.ic_gx_frame_delete, GxIconCategory.ANIMATION, listOf("remove frame")),
        GxIcon("frame-duplicate", R.drawable.ic_gx_frame_duplicate, GxIconCategory.ANIMATION, listOf("copy frame", "hold frame")),
        GxIcon("frame-rate", R.drawable.ic_gx_frame_rate, GxIconCategory.ANIMATION, listOf("fps", "frames per second")),
        GxIcon("keyframe", R.drawable.ic_gx_keyframe, GxIconCategory.ANIMATION, listOf("key state", "diamond marker")),
        GxIcon("keyframe-add", R.drawable.ic_gx_keyframe_add, GxIconCategory.ANIMATION, listOf("set key", "record state")),
        GxIcon("loop-playback", R.drawable.ic_gx_loop_playback, GxIconCategory.ANIMATION, listOf("repeat", "cycle")),
        GxIcon("motion-tween", R.drawable.ic_gx_motion_tween, GxIconCategory.ANIMATION, listOf("interpolate", "in between frames")),
        GxIcon("onion-skin", R.drawable.ic_gx_onion_skin, GxIconCategory.ANIMATION, listOf("ghost frames", "previous next frame")),
        GxIcon("pause", R.drawable.ic_gx_pause, GxIconCategory.ANIMATION, listOf("hold playback")),
        GxIcon("play", R.drawable.ic_gx_play, GxIconCategory.ANIMATION, listOf("run", "playback start")),
        GxIcon("step-backward", R.drawable.ic_gx_step_backward, GxIconCategory.ANIMATION, listOf("previous frame")),
        GxIcon("step-forward", R.drawable.ic_gx_step_forward, GxIconCategory.ANIMATION, listOf("next frame")),
        GxIcon("stop", R.drawable.ic_gx_stop, GxIconCategory.ANIMATION, listOf("end playback")),
        GxIcon("timeline", R.drawable.ic_gx_timeline, GxIconCategory.ANIMATION, listOf("frames track", "animation panel")),
        GxIcon("ar-view", R.drawable.ic_gx_ar_view, GxIconCategory.GENERATIVE, listOf("augmented reality", "camera overlay")),
        GxIcon("camera-capture", R.drawable.ic_gx_camera_capture, GxIconCategory.GENERATIVE, listOf("take photo", "reference photo")),
        GxIcon("edge-detect", R.drawable.ic_gx_edge_detect, GxIconCategory.GENERATIVE, listOf("canny", "outline extraction")),
        GxIcon("gallery-import", R.drawable.ic_gx_gallery_import, GxIconCategory.GENERATIVE, listOf("photo library", "import image")),
        GxIcon("generate", R.drawable.ic_gx_generate, GxIconCategory.GENERATIVE, listOf("ai generate", "text to image")),
        GxIcon("generate-expand", R.drawable.ic_gx_generate_expand, GxIconCategory.GENERATIVE, listOf("ai outpaint", "generative expand")),
        GxIcon("generate-remove", R.drawable.ic_gx_generate_remove, GxIconCategory.GENERATIVE, listOf("ai remove", "smart erase")),
        GxIcon("generate-variations", R.drawable.ic_gx_generate_variations, GxIconCategory.GENERATIVE, listOf("ai variations", "reroll")),
        GxIcon("mural-scale", R.drawable.ic_gx_mural_scale, GxIconCategory.GENERATIVE, listOf("wall scale", "project size")),
        GxIcon("prompt", R.drawable.ic_gx_prompt, GxIconCategory.GENERATIVE, listOf("ai text input", "describe")),
        GxIcon("registration-mark", R.drawable.ic_gx_registration_mark, GxIconCategory.GENERATIVE, listOf("alignment target", "print register")),
        GxIcon("stencil", R.drawable.ic_gx_stencil, GxIconCategory.GENERATIVE, listOf("screen mask", "spray template")),
        GxIcon("stencil-layers", R.drawable.ic_gx_stencil_layers, GxIconCategory.GENERATIVE, listOf("multi layer stencil", "registration")),
        GxIcon("style-transfer", R.drawable.ic_gx_style_transfer, GxIconCategory.GENERATIVE, listOf("ai style", "restyle")),
        GxIcon("subject-isolate", R.drawable.ic_gx_subject_isolate, GxIconCategory.GENERATIVE, listOf("ml cutout", "background removal")),
        GxIcon("upscale", R.drawable.ic_gx_upscale, GxIconCategory.GENERATIVE, listOf("ai upscale", "super resolution")),
        GxIcon("account", R.drawable.ic_gx_account, GxIconCategory.UI, listOf("profile", "user")),
        GxIcon("back", R.drawable.ic_gx_back, GxIconCategory.UI, listOf("navigate back", "previous screen")),
        GxIcon("brush-cursor", R.drawable.ic_gx_brush_cursor, GxIconCategory.UI, listOf("custom cursor", "tool preview")),
        GxIcon("chevron-down", R.drawable.ic_gx_chevron_down, GxIconCategory.UI, listOf("expand", "dropdown")),
        GxIcon("chevron-up", R.drawable.ic_gx_chevron_up, GxIconCategory.UI, listOf("collapse", "close dropdown")),
        GxIcon("close", R.drawable.ic_gx_close, GxIconCategory.UI, listOf("x", "dismiss", "cancel")),
        GxIcon("cloud-offline", R.drawable.ic_gx_cloud_offline, GxIconCategory.UI, listOf("no connection", "local only")),
        GxIcon("cloud-sync", R.drawable.ic_gx_cloud_sync, GxIconCategory.UI, listOf("backup", "cloud save")),
        GxIcon("collaborators", R.drawable.ic_gx_collaborators, GxIconCategory.UI, listOf("shared users", "team")),
        GxIcon("comment", R.drawable.ic_gx_comment, GxIconCategory.UI, listOf("annotation", "leave a note")),
        GxIcon("copy-link", R.drawable.ic_gx_copy_link, GxIconCategory.UI, listOf("copy url", "share link")),
        GxIcon("download", R.drawable.ic_gx_download, GxIconCategory.UI, listOf("save to device", "export local")),
        GxIcon("error", R.drawable.ic_gx_error, GxIconCategory.UI, listOf("failure", "problem")),
        GxIcon("forward", R.drawable.ic_gx_forward, GxIconCategory.UI, listOf("navigate forward", "next screen")),
        GxIcon("gesture-pinch", R.drawable.ic_gx_gesture_pinch, GxIconCategory.UI, listOf("two finger zoom")),
        GxIcon("gesture-two-finger-tap", R.drawable.ic_gx_gesture_two_finger_tap, GxIconCategory.UI, listOf("undo gesture", "quick undo")),
        GxIcon("help", R.drawable.ic_gx_help, GxIconCategory.UI, listOf("question", "support")),
        GxIcon("info", R.drawable.ic_gx_info, GxIconCategory.UI, listOf("about", "help detail")),
        GxIcon("keyboard-shortcut", R.drawable.ic_gx_keyboard_shortcut, GxIconCategory.UI, listOf("hotkeys", "key command")),
        GxIcon("language", R.drawable.ic_gx_language, GxIconCategory.UI, listOf("locale", "translate")),
        GxIcon("link-external", R.drawable.ic_gx_link_external, GxIconCategory.UI, listOf("open in browser", "outbound")),
        GxIcon("menu", R.drawable.ic_gx_menu, GxIconCategory.UI, listOf("hamburger", "nav rail", "more")),
        GxIcon("more-horizontal", R.drawable.ic_gx_more_horizontal, GxIconCategory.UI, listOf("overflow menu", "kebab horizontal")),
        GxIcon("more-vertical", R.drawable.ic_gx_more_vertical, GxIconCategory.UI, listOf("overflow menu", "kebab vertical")),
        GxIcon("notification", R.drawable.ic_gx_notification, GxIconCategory.UI, listOf("bell", "alerts")),
        GxIcon("search", R.drawable.ic_gx_search, GxIconCategory.UI, listOf("find", "magnifier")),
        GxIcon("settings", R.drawable.ic_gx_settings, GxIconCategory.UI, listOf("preferences", "gear")),
        GxIcon("share", R.drawable.ic_gx_share, GxIconCategory.UI, listOf("send", "export to app")),
        GxIcon("subscription", R.drawable.ic_gx_subscription, GxIconCategory.UI, listOf("upgrade", "pro badge")),
        GxIcon("success", R.drawable.ic_gx_success, GxIconCategory.UI, listOf("done", "confirmed")),
        GxIcon("theme-toggle", R.drawable.ic_gx_theme_toggle, GxIconCategory.UI, listOf("dark mode", "light mode")),
        GxIcon("undo-history-slider", R.drawable.ic_gx_undo_history_slider, GxIconCategory.UI, listOf("scrub history", "time slider")),
        GxIcon("upload", R.drawable.ic_gx_upload, GxIconCategory.UI, listOf("import", "add file")),
        GxIcon("warning", R.drawable.ic_gx_warning, GxIconCategory.UI, listOf("caution", "alert")),
    )

    private val byKey: Map<String, GxIcon> = all.associateBy { it.key }

    /** Look an icon up by its stable key, e.g. `"layer-mask-add"`. */
    operator fun get(key: String): GxIcon? = byKey[key]

    /** Every icon in one family, in authored order. */
    fun inCategory(category: GxIconCategory): List<GxIcon> = all.filter { it.category == category }

    /** Case-insensitive search across keys and keywords, for an icon picker. */
    fun search(query: String): List<GxIcon> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return all
        return all.filter { icon ->
            icon.key.contains(q) || icon.keywords.any { it.contains(q) }
        }
    }
}
