"""Build every icon output from the masters.

The masters in `masters/` are the drawings; this turns them into the three things that ship:
an Android VectorDrawable per icon, a typed Kotlin registry, and a contact sheet to review
them on. Nothing here draws anything — a change to a glyph is a change to its master.

The drawings arrive from a design package rather than being generated here, which moves the
job from *emitting* geometry to *checking* it. Two of the checks earn their place:

**Bounds** are measured off flattened curves, not control points. A Bézier's control polygon
can sit most of a unit outside the curve it describes, so control-point bounds flag glyphs
that are fine and miss glyphs that are not.

**Collisions** are found by rendering, not by comparing markup. Two icons in the delivered
set differed only by a line drawn exactly along an edge another shape already had; several
more differed only in `<circle>` elements, which a scan of `d` attributes cannot see at all.
A silhouette hash over the drawn geometry catches both, and it is the check that matters
most here: 404 icons is well past the number anyone can hold in their head, and two keys
that look the same are indistinguishable to the person using the app.
"""

from __future__ import annotations

import hashlib
import html
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

import svgpath  # noqa: E402
from grid import (  # noqa: E402
    BLEED, BUDGET, BUDGET_FILLED, CAP, CATEGORIES, HATCH_PHASE, HATCH_PITCH, HATCH_WEIGHT, JOIN, LIVE,
    STROKE, VIEW, hatch_lines,
)

MASTERS = os.path.join(HERE, "masters")
META_PATH = os.path.join(HERE, "meta.json")
DIST = os.path.join(HERE, "dist")
DRAWABLE_DIR = os.path.join(ROOT, "core", "design", "src", "main", "res", "drawable")
KOTLIN_PATH = os.path.join(
    ROOT, "core", "design", "src", "main", "java", "com", "hereliesaz", "graffitixr",
    "design", "GraffuxIcons.kt",
)
NOTICE_PATH = os.path.join(HERE, "NOTICE")
# The same notice, as an app resource. MIT asks for it to be included in copies of the
# software, and a file that only exists in the repository does not travel with the binary.
NOTICE_RES = os.path.join(ROOT, "app", "src", "main", "res", "raw", "notice_icons.txt")

PHOSPHOR_MIT = """MIT License

Copyright (c) 2023 Phosphor Icons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

PREFIX = "ic_gx_"
GENERATED = "Generated by branding/icons/build.py — edit the drawing in branding/icons/masters/, not this file."


def res_name(key: str) -> str:
    return PREFIX + key.replace("-", "_")


def pascal(key: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in key.split("-"))


# ---------------------------------------------------------------------------------------
# Reading a master
# ---------------------------------------------------------------------------------------


class Shape:
    """One drawn path, with its fill and stroke already resolved."""

    __slots__ = ("d", "fill", "stroke", "extras", "_polys")

    def __init__(self, d, fill, stroke, extras):
        self.d, self.fill, self.stroke, self.extras = d, fill, stroke, extras
        self._polys = None

    @property
    def polys(self):
        if self._polys is None:
            self._polys = svgpath.flatten(svgpath.parse(self.d))
        return self._polys

    @property
    def ruled(self) -> bool:
        return self.fill.startswith("url(")

    def bbox(self):
        return svgpath.bbox(self.polys)


def read_master(path, key):
    root = ET.parse(path).getroot()
    vb = root.get("viewBox", "").split()
    if [float(v) for v in vb] != [0.0, 0.0, VIEW, VIEW]:
        raise ValueError(f"viewBox is {root.get('viewBox')!r}, expected 0 0 {int(VIEW)} {int(VIEW)}")
    shapes = []
    for el in root:
        if el.tag.split("}")[-1] != "path":
            continue
        d = el.get("d")
        if not d:
            continue
        extras = {k: v for k, v in el.attrib.items()
                  if k in ("fill-rule", "stroke-width", "stroke-linecap", "stroke-linejoin")}
        shapes.append(Shape(d, el.get("fill", "none"), el.get("stroke", "currentColor"), extras))
    if not shapes:
        raise ValueError("no paths")
    return shapes


def load():
    meta = json.load(open(META_PATH, encoding="utf-8"))
    order = {k: i for i, (k, _, _) in enumerate(CATEGORIES)}
    icons = []
    for fn in sorted(os.listdir(MASTERS)):
        if not fn.endswith(".svg"):
            continue
        key = fn[:-4]
        info = meta.get(key)
        if info is None:
            raise SystemExit(f"{key}: no entry in meta.json — re-run import_package.py")
        icons.append({
            "key": key,
            "cat": info["category"],
            "kw": info.get("keywords", []),
            "source": info.get("source", "graffux"),
            "shapes": read_master(os.path.join(MASTERS, fn), key),
        })
    icons.sort(key=lambda ic: (order.get(ic["cat"], 99), ic["key"]))
    return icons


# ---------------------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------------------


def silhouette(ic) -> str:
    """A hash of what the icon actually draws, ignoring how the file says it.

    Geometry is flattened first, so a circle written as `<circle>`, as two arcs, or as four
    cubics all hash alike, and rounded to a fifth of a unit so that a coordinate rewritten
    at a different precision is not mistaken for a different drawing. Fill and stroke are
    folded in: two identical outlines, one ruled and one not, are two different drawings.
    """
    marks = []
    for sh in ic["shapes"]:
        pts = ";".join(f"{round(x * 5) / 5:g},{round(y * 5) / 5:g}"
                       for poly in sh.polys for x, y in poly)
        kind = "ruled" if sh.ruled else ("filled" if sh.fill != "none" else "")
        marks.append(f"{kind}|{'stroked' if sh.stroke != 'none' else ''}|{pts}")
    return hashlib.md5("\n".join(sorted(marks)).encode()).hexdigest()


def validate(icons):
    errors, warnings = [], []
    for ic in icons:
        key = ic["key"]
        if not key.replace("-", "").isalnum() or not key[0].isalpha():
            errors.append(f"{key}: key must be alphanumeric kebab-case starting with a letter")
        if ic["cat"] not in {c for c, _, _ in CATEGORIES}:
            errors.append(f"{key}: category {ic['cat']!r} is not one of the {len(CATEGORIES)} families")

        boxes = [sh.bbox() for sh in ic["shapes"] if sh.bbox()]
        if not boxes:
            errors.append(f"{key}: empty glyph")
            continue
        x0 = min(b[0] for b in boxes); y0 = min(b[1] for b in boxes)
        x1 = max(b[2] for b in boxes); y1 = max(b[3] for b in boxes)
        if x0 < BLEED[0] - 1e-6 or y0 < BLEED[0] - 1e-6 or x1 > BLEED[1] + 1e-6 or y1 > BLEED[1] + 1e-6:
            errors.append(f"{key}: geometry {x0:.2f},{y0:.2f}..{x1:.2f},{y1:.2f} escapes the bleed {BLEED}")
        elif x0 < LIVE[0] - 1e-6 or y0 < LIVE[0] - 1e-6 or x1 > LIVE[1] + 1e-6 or y1 > LIVE[1] + 1e-6:
            warnings.append(f"{key}: geometry reaches into the bleed margin")
        if (x1 - x0) < 6 and (y1 - y0) < 6:
            warnings.append(f"{key}: glyph is only {x1 - x0:.1f}×{y1 - y0:.1f} — too small to read as deliberate")

        weight = sum(len(sh.d) for sh in ic["shapes"])
        outlined = any(sh.stroke != "none" for sh in ic["shapes"])
        budget = BUDGET if outlined else BUDGET_FILLED
        if weight > budget:
            warnings.append(f"{key}: {weight} chars of path data (budget {budget}) — cut something")

        for sh in ic["shapes"]:
            if sh.ruled and sh.fill != f"url(#{hatch_id(key)})":
                errors.append(f"{key}: ruled path points at {sh.fill}, not this icon's own pattern")

    # Two keys that draw the same thing are indistinguishable in a picker, whatever the
    # markup says. This is an error, not a warning: it always means one of them is wrong.
    seen = {}
    for ic in icons:
        seen.setdefault(silhouette(ic), []).append(ic["key"])
    for group in seen.values():
        if len(group) > 1:
            errors.append("identical drawings: " + " = ".join(sorted(group)))
    return errors, warnings


# ---------------------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------------------


def hatch_id(key: str) -> str:
    return "gfxHatch-" + key


def _num(v):
    return svgpath.fmt(v)


def svg_defs(key, icon_shapes, indent="  "):
    if not any(sh.ruled for sh in icon_shapes):
        return ""
    y = HATCH_PHASE * HATCH_PITCH
    return (
        f"{indent}<defs>\n"
        f'{indent}  <pattern id="{hatch_id(key)}" patternUnits="userSpaceOnUse"\n'
        f'{indent}           width="{_num(HATCH_PITCH * 4)}" height="{_num(HATCH_PITCH)}">\n'
        f'{indent}    <line x1="0" y1="{_num(y)}" x2="{_num(HATCH_PITCH * 4)}" y2="{_num(y)}"\n'
        f'{indent}          stroke="currentColor" stroke-width="{HATCH_WEIGHT}"/>\n'
        f"{indent}  </pattern>\n"
        f"{indent}</defs>\n"
    )


def svg_body(shapes, indent="  "):
    out = []
    for sh in shapes:
        attrs = [f'd="{sh.d}"']
        if sh.fill != "none":
            attrs.append(f'fill="{sh.fill}"')
        if sh.stroke == "none":
            attrs.append('stroke="none"')
        for k, v in sh.extras.items():
            attrs.append(f'{k}="{v}"')
        out.append(f"{indent}<path " + " ".join(attrs) + "/>")
    return "\n".join(out)


def vector_drawable(ic):
    key = ic["key"]
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- " + GENERATED + " -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{int(VIEW)}dp"',
        f'    android:height="{int(VIEW)}dp"',
        f'    android:viewportWidth="{int(VIEW)}"',
        f'    android:viewportHeight="{int(VIEW)}"',
        '    android:tint="?attr/colorControlNormal">',
        f"    <!-- {key} — {ic['source']} -->",
    ]
    for sh in ic["shapes"]:
        if sh.ruled:
            lines += vector_hatch(sh)
        elif sh.fill != "none":
            lines += ["    <path", '        android:fillColor="@android:color/white"']
            if sh.extras.get("fill-rule") == "evenodd":
                lines.append('        android:fillType="evenOdd"')
            lines.append(f'        android:pathData="{sh.d}" />')
        # A path can be both filled and stroked, so the stroke is its own emission rather
        # than an else-branch — dropping it silently un-outlines every ruled container.
        if sh.stroke != "none":
            lines += [
                "    <path",
                '        android:fillColor="@android:color/transparent"',
                '        android:strokeColor="@android:color/white"',
                f'        android:strokeWidth="{sh.extras.get("stroke-width", STROKE)}"',
                f'        android:strokeLineCap="{sh.extras.get("stroke-linecap", CAP)}"',
                f'        android:strokeLineJoin="{sh.extras.get("stroke-linejoin", JOIN)}"',
                f'        android:pathData="{sh.d}" />',
            ]
    lines.append("</vector>")
    return "\n".join(lines) + "\n"


def vector_hatch(sh):
    """A ruled region, as a clipped group of real lines.

    VectorDrawable has no pattern fill, so the rules have to be geometry. They are clipped
    to the region rather than trimmed to it, which keeps the line coordinates on the shared
    viewport grid — the same rules the SVG pattern lays down, at the same y values.

    Two consequences worth knowing before shipping a change here: the drawables get longer
    (a full-height region is twenty-odd extra paths), and VectorDrawable clip paths are not
    antialiased on every Android version, so a ruled edge can look harder than its SVG.
    """
    x0, y0, x1, y1 = sh.bbox()
    out = ["    <group>", f'        <clip-path android:pathData="{sh.d}" />']
    for y in hatch_lines(y0, y1):
        out += [
            "        <path",
            '            android:strokeColor="@android:color/white"',
            f'            android:strokeWidth="{HATCH_WEIGHT}"',
            f'            android:pathData="M{_num(x0)},{_num(y)}L{_num(x1)},{_num(y)}" />',
        ]
    out.append("    </group>")
    return out


def kotlin_registry(icons):
    cat_enum = ", ".join(c[0].upper() for c in CATEGORIES)
    props, entries = [], []
    for ic in icons:
        props.append(f"    /** `{ic['key']}` — {ic['cat']}. */")
        props.append(f"    val {pascal(ic['key'])}: Int get() = R.drawable.{res_name(ic['key'])}")
        kw = ", ".join(f'"{k}"' for k in ic["kw"])
        entries.append(
            f'        GxIcon("{ic["key"]}", R.drawable.{res_name(ic["key"])}, '
            f"GxIconCategory.{ic['cat'].upper()}, listOf({kw})),"
        )
    ruled = sum(1 for ic in icons if any(sh.ruled for sh in ic["shapes"]))
    return "\n".join([
        "package com.hereliesaz.graffitixr.design",
        "",
        "import androidx.annotation.DrawableRes",
        "",
        "// " + GENERATED,
        "",
        "/** The families the Graffux icon set is divided into. */",
        f"enum class GxIconCategory {{ {cat_enum} }}",
        "",
        "/** One icon: its stable key, its drawable, and what it can be searched by. */",
        "data class GxIcon(",
        "    val key: String,",
        "    @param:DrawableRes val res: Int,",
        "    val category: GxIconCategory,",
        "    val keywords: List<String>,",
        ")",
        "",
        "/**",
        " * The Graffux icon set.",
        " *",
        f" * {len(icons)} glyphs on a {int(VIEW)}-unit grid at one {STROKE}-unit stroke weight, outline first.",
        f" * {ruled} of them rule a region rather than filling it: rows of parallel lines at a fixed",
        " * pitch, anchored to the viewport rather than to the region, so that any two ruled icons",
        " * side by side read as ruled from the same plate.",
        " *",
        " * Reference them directly (`GraffuxIcons.Brush`) or look them up by key for a picker.",
        " */",
        "object GraffuxIcons {",
        "",
        "\n".join(props),
        "",
        "    /** Every icon, grouped by family. */",
        "    val all: List<GxIcon> = listOf(",
        "\n".join(entries),
        "    )",
        "",
        "    private val byKey: Map<String, GxIcon> = all.associateBy { it.key }",
        "",
        "    /** Look an icon up by its stable key, e.g. `\"layer-mask-add\"`. */",
        "    operator fun get(key: String): GxIcon? = byKey[key]",
        "",
        "    /** Every icon in one family, in authored order. */",
        "    fun inCategory(category: GxIconCategory): List<GxIcon> = all.filter { it.category == category }",
        "",
        "    /** Case-insensitive search across keys and keywords, for an icon picker. */",
        "    fun search(query: String): List<GxIcon> {",
        "        val q = query.trim().lowercase()",
        "        if (q.isEmpty()) return all",
        "        return all.filter { icon ->",
        "            icon.key.contains(q) || icon.keywords.any { it.contains(q) }",
        "        }",
        "    }",
        "}",
        "",
    ])


# ---------------------------------------------------------------------------------------
# Contact sheet
# ---------------------------------------------------------------------------------------

SHEET_CSS = """
:root {
  --ink: #f2f2f0; --ground: #0d0d0f; --dim: #74747c; --rule: #22222a;
  --hot: #ff3b1f; --cool: #2f6bff; --card: #131318;
}
@media (prefers-color-scheme: light) {
  :root { --ink: #14141a; --ground: #f7f7f5; --dim: #6c6c74; --rule: #dedee4; --card: #ffffff; }
}
:root[data-theme="light"] { --ink: #14141a; --ground: #f7f7f5; --dim: #6c6c74; --rule: #dedee4; --card: #fff; }
:root[data-theme="dark"] { --ink: #f2f2f0; --ground: #0d0d0f; --dim: #74747c; --rule: #22222a; --card: #131318; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--ground); color: var(--ink);
  font: 14px/1.5 ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif; }
.wrap { max-width: 1180px; margin: 0 auto; padding: 40px 20px 96px; }
header { border-bottom: 1px solid var(--rule); padding-bottom: 22px; margin-bottom: 26px; }
h1 { font-size: 26px; margin: 0 0 6px; letter-spacing: -0.015em; }
.sub { color: var(--dim); font-size: 13px; margin: 0; }
.meta { display: flex; flex-wrap: wrap; gap: 8px 22px; margin-top: 16px;
  font: 11px/1.4 ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--dim); }
.meta b { color: var(--ink); font-weight: 600; }
.controls { position: sticky; top: 0; z-index: 5; background: var(--ground);
  padding: 12px 0; border-bottom: 1px solid var(--rule); margin-bottom: 26px;
  display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }
input[type=search] { flex: 1 1 240px; min-width: 0; background: var(--card); color: var(--ink);
  border: 1px solid var(--rule); border-radius: 7px; padding: 9px 12px; font-size: 14px; }
input[type=search]:focus { outline: 2px solid var(--cool); outline-offset: -1px; }
.toggle { display: inline-flex; align-items: center; gap: 7px; color: var(--dim); font-size: 12px;
  background: var(--card); border: 1px solid var(--rule); border-radius: 7px; padding: 8px 12px; cursor: pointer; }
h2 { font-size: 12px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--dim);
  margin: 38px 0 4px; font-weight: 600; }
h2 .n { color: var(--hot); }
.blurb { color: var(--dim); font-size: 12px; margin: 0 0 16px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(116px, 1fr)); gap: 6px; }
.cell { background: var(--card); border: 1px solid var(--rule); border-radius: 9px;
  padding: 14px 8px 10px; text-align: center; overflow: hidden; }
.cell .art { display: flex; align-items: flex-end; justify-content: center; gap: 10px; height: 34px; }
.cell svg { color: var(--ink); display: block; }
.cell .k { margin-top: 9px; font: 10px/1.35 ui-monospace, SFMono-Regular, Menlo, monospace;
  color: var(--dim); word-break: break-word; }
.cell .apps { font: 9px/1 ui-monospace, monospace; margin-top: 4px; letter-spacing: .06em;
  color: color-mix(in srgb, var(--dim) 55%, transparent); }
.cell:hover { border-color: var(--cool); }
.cell:hover .k { color: var(--ink); }
body.grid-on .cell .art { background-image:
  linear-gradient(to right, color-mix(in srgb, var(--cool) 22%, transparent) 1px, transparent 1px),
  linear-gradient(to bottom, color-mix(in srgb, var(--cool) 22%, transparent) 1px, transparent 1px);
  background-size: 4px 4px; background-position: center bottom; }
.empty { color: var(--dim); padding: 40px 0; text-align: center; }
footer { margin-top: 56px; padding-top: 18px; border-top: 1px solid var(--rule);
  color: var(--dim); font-size: 11px; font-family: ui-monospace, monospace; }
"""

SHEET_JS = """
const q = document.getElementById('q');
const cells = [...document.querySelectorAll('.cell')];
const sections = [...document.querySelectorAll('section')];
function apply() {
  const v = q.value.trim().toLowerCase();
  cells.forEach(c => { c.hidden = v !== '' && !c.dataset.s.includes(v); });
  sections.forEach(s => {
    const shown = [...s.querySelectorAll('.cell')].filter(c => !c.hidden).length;
    s.hidden = shown === 0;
    const n = s.querySelector('h2 .n'); if (n) n.textContent = shown;
  });
  document.getElementById('empty').hidden = cells.some(c => !c.hidden);
}
q.addEventListener('input', apply);
document.getElementById('gridToggle').addEventListener('click', () => {
  document.body.classList.toggle('grid-on');
});
"""

def contact_sheet(icons):
    by_cat = {}
    for ic in icons:
        by_cat.setdefault(ic["cat"], []).append(ic)
    ruled = sum(1 for ic in icons if any(sh.ruled for sh in ic["shapes"]))
    borrowed = sum(1 for ic in icons if ic["source"].startswith("phosphor"))

    out = [
        "<title>Graffux Icons</title>",
        f"<style>{SHEET_CSS}</style>",
        '<div class="wrap">',
        "<header>",
        "<h1>Graffux icon set</h1>",
        '<p class="sub">One stroke weight, one grid, outline first — ruled rather than filled '
        "wherever a region has room for rule. Built for a phone screen at arm's length.</p>",
        '<div class="meta">'
        f"<span><b>{len(icons)}</b> icons</span>"
        f"<span><b>{len(by_cat)}</b> families</span>"
        f"<span><b>{ruled}</b> ruled</span>"
        f"<span><b>{borrowed}</b> from Phosphor</span>"
        f"<span>grid <b>{int(VIEW)}×{int(VIEW)}</b></span>"
        f"<span>stroke <b>{STROKE}</b></span>"
        f"<span>hatch <b>{HATCH_PITCH} / {HATCH_WEIGHT}</b></span>"
        "</div>",
        "</header>",
        '<div class="controls">',
        '<input id="q" type="search" placeholder="Search name, keyword, or family…" autocomplete="off">',
        '<button class="toggle" id="gridToggle" type="button">4-unit grid</button>',
        "</div>",
    ]

    for key, title, blurb in CATEGORIES:
        group = by_cat.get(key, [])
        if not group:
            continue
        out.append(f'<section data-cat="{key}">')
        out.append(f'<h2>{html.escape(title)} · <span class="n">{len(group)}</span></h2>')
        out.append(f'<p class="blurb">{html.escape(blurb)}</p>')
        out.append('<div class="grid">')
        for ic in group:
            search = " ".join([ic["key"], key, title, ic["source"], *ic["kw"]]).lower()
            # The pattern id carries the icon's key, so 404 of these coexist in one
            # document. It is declared once, in the 24px copy; both sizes reference it and
            # share a viewBox, so the rules land on the same grid in each.
            body = svg_body(ic["shapes"], indent="")
            defs = svg_defs(ic["key"], ic["shapes"], indent="")
            svg_attrs = (
                f'viewBox="0 0 {int(VIEW)} {int(VIEW)}" fill="none" stroke="currentColor" '
                f'stroke-width="{STROKE}" stroke-linecap="{CAP}" stroke-linejoin="{JOIN}"'
            )
            out.append(
                f'<div class="cell" data-s="{html.escape(search, quote=True)}" '
                f'title="{html.escape(ic["source"], quote=True)}">'
                f'<div class="art">'
                f'<svg width="24" height="24" {svg_attrs}>{defs}{body}</svg>'
                f'<svg width="16" height="16" {svg_attrs}>{body}</svg>'
                f"</div>"
                f'<div class="k">{html.escape(ic["key"])}</div>'
                f'<div class="apps">{html.escape(ic["source"].replace("phosphor/", "ph "))}</div>'
                "</div>"
            )
        out.append("</div></section>")

    out += [
        '<p class="empty" id="empty" hidden>Nothing matches that.</p>',
        "<footer>Each cell shows the glyph at 24px and at 16px. "
        "If it only works at 24, it does not work.</footer>",
        "</div>",
        f"<script>{SHEET_JS}</script>",
    ]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------


def notice(icons):
    """Third-party attribution, generated so the list of borrowed icons cannot go stale."""
    borrowed = sorted((ic["key"], ic["source"].split("/", 1)[1])
                      for ic in icons if ic["source"].startswith("phosphor/"))
    mine = len(icons) - len(borrowed)
    out = [
        "Third-party notices for the Graffux icon set",
        "============================================",
        "",
        f"{len(borrowed)} of the {len(icons)} icons in this set are drawings from Phosphor Icons, used as",
        f"delivered. The remaining {mine} are Graffux's own.",
        "",
        "Phosphor's licence is MIT, which requires this notice to travel with any copy of the",
        "geometry — a shipped app binary included, not only this repository. It is generated by",
        "branding/icons/build.py from the set's own manifest, so the list below cannot drift",
        "from what actually ships, and a copy is written to the app's resources.",
        "",
        "",
        "Phosphor Icons",
        "--------------",
        "",
        "https://github.com/phosphor-icons/core",
        "",
        PHOSPHOR_MIT,
        "",
        "",
        "Which icons",
        "-----------",
        "",
        f"The {len(borrowed)} Graffux keys below are Phosphor drawings. Each is also recorded in",
        "dist/icons.json and in the comment at the top of its master.",
        "",
    ]
    width = max(len(k) for k, _ in borrowed)
    out += [f"  {k.ljust(width)}  {n}" for k, n in borrowed]
    return "\n".join(out) + "\n"


def clean_stale(icons):
    live = {res_name(ic["key"]) + ".xml" for ic in icons}
    removed = 0
    if os.path.isdir(DRAWABLE_DIR):
        for fn in os.listdir(DRAWABLE_DIR):
            if fn.startswith(PREFIX) and fn not in live:
                os.remove(os.path.join(DRAWABLE_DIR, fn))
                removed += 1
    return removed


def main():
    icons = load()
    errors, warnings = validate(icons)
    for w in warnings:
        print(f"  warn  {w}")
    if errors:
        for e in errors:
            print(f"  ERROR {e}", file=sys.stderr)
        return 1

    os.makedirs(DIST, exist_ok=True)
    os.makedirs(DRAWABLE_DIR, exist_ok=True)
    stale = clean_stale(icons)

    for ic in icons:
        with open(os.path.join(DRAWABLE_DIR, res_name(ic["key"]) + ".xml"), "w", encoding="utf-8") as fh:
            fh.write(vector_drawable(ic))

    manifest = {
        "grid": {
            "view": VIEW, "live": list(LIVE), "stroke": STROKE, "cap": CAP, "join": JOIN,
            "hatch": {"pitch": HATCH_PITCH, "weight": HATCH_WEIGHT, "phase": HATCH_PHASE},
        },
        "categories": [{"key": k, "title": t, "blurb": b} for k, t, b in CATEGORIES],
        "icons": [
            {
                "key": ic["key"],
                "category": ic["cat"],
                "drawable": res_name(ic["key"]),
                "keywords": ic["kw"],
                "master": f"masters/{ic['key']}.svg",
                "ruled": any(sh.ruled for sh in ic["shapes"]),
                "source": ic["source"],
            }
            for ic in icons
        ],
    }
    with open(os.path.join(DIST, "icons.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    with open(os.path.join(DIST, "contact-sheet.html"), "w", encoding="utf-8") as fh:
        fh.write(contact_sheet(icons))

    os.makedirs(os.path.dirname(KOTLIN_PATH), exist_ok=True)
    with open(KOTLIN_PATH, "w", encoding="utf-8") as fh:
        fh.write(kotlin_registry(icons))

    text = notice(icons)
    os.makedirs(os.path.dirname(NOTICE_RES), exist_ok=True)
    for path in (NOTICE_PATH, NOTICE_RES):
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)

    counts = {}
    for ic in icons:
        counts[ic["cat"]] = counts.get(ic["cat"], 0) + 1
    borrowed = sum(1 for ic in icons if ic["source"].startswith("phosphor"))
    ruled = sum(1 for ic in icons if any(sh.ruled for sh in ic["shapes"]))
    print(f"\n{len(icons)} icons across {len(counts)} families"
          + (f", {stale} stale drawable(s) removed" if stale else ""))
    for k, t, _ in CATEGORIES:
        if k in counts:
            print(f"  {counts[k]:>4}  {t}")
    print(f"\n{ruled} ruled, {borrowed} drawn by Phosphor (MIT — see NOTICE)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
