#!/usr/bin/env python3
"""Build the Graffux icon set.

Reads the authored geometry in `sets/`, validates it against the design system, and emits:

  branding/icons/dist/svg/<key>.svg                       — masters, for design tools
  branding/icons/dist/icons.json                          — the manifest (keys, categories, keywords)
  branding/icons/dist/contact-sheet.html                  — reviewable sheet, 24px and 16px
  core/design/src/main/res/drawable/ic_gx_<key>.xml       — Android VectorDrawables
  core/design/.../design/GraffuxIcons.kt                  — typed registry for Compose

Run from anywhere:  python3 branding/icons/build.py
"""

from __future__ import annotations

import html
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

from kit import BLEED, BUDGET, CAP, ICONS, JOIN, LIVE, STROKE, VIEW, CATEGORIES  # noqa: E402

import sets  # noqa: E402,F401  (importing the package registers every icon)

DIST = os.path.join(HERE, "dist")
SVG_DIR = os.path.join(DIST, "svg")
DRAWABLE_DIR = os.path.join(ROOT, "core", "design", "src", "main", "res", "drawable")
KOTLIN_PATH = os.path.join(
    ROOT, "core", "design", "src", "main", "java", "com", "hereliesaz", "graffitixr",
    "design", "GraffuxIcons.kt",
)

PREFIX = "ic_gx_"
GENERATED = "Generated by branding/icons/build.py — edit the geometry in branding/icons/sets/, not this file."


# ---------------------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------------------


def res_name(key: str) -> str:
    return PREFIX + key.replace("-", "_")


def pascal(key: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in key.split("-"))


# ---------------------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------------------


def validate(icons):
    errors, warnings = [], []
    for ic in icons:
        key = ic["key"]
        if not ic["strokes"] and not ic["fills"]:
            errors.append(f"{key}: empty glyph")
            continue
        if not key.replace("-", "").isalnum() or not key[0].isalpha():
            errors.append(f"{key}: key must be alphanumeric kebab-case starting with a letter")
        if len(ic["fills"]) > 1:
            warnings.append(f"{key}: {len(ic['fills'])} fill paths — an icon gets one keystone")

        pts = [p for path in ic["strokes"] + ic["fills"] for p in path.pts]
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        x0, y0, x1, y1 = min(xs), min(ys), max(xs), max(ys)
        if x0 < BLEED[0] - 1e-6 or y0 < BLEED[0] - 1e-6 or x1 > BLEED[1] + 1e-6 or y1 > BLEED[1] + 1e-6:
            errors.append(f"{key}: geometry {x0:.2f},{y0:.2f}..{x1:.2f},{y1:.2f} escapes the bleed {BLEED}")
        elif x0 < LIVE[0] - 1e-6 or y0 < LIVE[0] - 1e-6 or x1 > LIVE[1] + 1e-6 or y1 > LIVE[1] + 1e-6:
            warnings.append(f"{key}: geometry reaches into the bleed margin")

        # An icon that occupies a corner of the grid and nothing else reads as broken at 16px.
        if (x1 - x0) < 6 and (y1 - y0) < 6:
            warnings.append(f"{key}: glyph is only {x1 - x0:.1f}×{y1 - y0:.1f} — too small to read as deliberate")

        # Minimalism is a constraint, not a preference: a glyph that needs more than a
        # couple of hundred characters of path data is describing, not signalling.
        weight = sum(len(p.d) for p in ic["strokes"] + ic["fills"])
        if weight > BUDGET:
            warnings.append(f"{key}: {weight} chars of path data (budget {BUDGET}) — cut something")

        # Anything the three apps already have must say whose metaphor it inherits.
        if ic["apps"] != "new" and not ic["basis"]:
            errors.append(f"{key}: claims lineage ({ic['apps']}) but records no basis")
        # "new" + basis is fine when the lineage is Graffux's own (GraffitiXR) or a named
        # feature none of PS/AI/PR actually ships as an icon — only flag the ambiguous case
        # where the basis text itself claims one of the three apps' tools.
        if ic["apps"] == "new" and ic["basis"] and any(
            app in ic["basis"] for app in ("Photoshop's", "Illustrator's", "Procreate's")
        ):
            warnings.append(f"{key}: basis names an app tool but apps is \"new\" — check attribution")
    return errors, warnings


# ---------------------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------------------


def svg_body(ic, indent="  "):
    out = []
    for p in ic["strokes"]:
        out.append(f'{indent}<path d="{p.d}"/>')
    for p in ic["fills"]:
        rule = ' fill-rule="evenodd"' if p.evenodd else ""
        out.append(f'{indent}<path d="{p.d}" fill="currentColor" stroke="none"{rule}/>')
    return "\n".join(out)


def svg_document(ic):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(VIEW)} {int(VIEW)}"\n'
        f'     width="{int(VIEW)}" height="{int(VIEW)}" fill="none" stroke="currentColor"\n'
        f'     stroke-width="{STROKE}" stroke-linecap="{CAP}" stroke-linejoin="{JOIN}">\n'
        f"  <!-- graffux/{ic['key']} — {ic['note']} -->\n"
        f"{svg_body(ic)}\n"
        f"</svg>\n"
    )


def vector_drawable(ic):
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- " + GENERATED + " -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{int(VIEW)}dp"',
        f'    android:height="{int(VIEW)}dp"',
        f'    android:viewportWidth="{int(VIEW)}"',
        f'    android:viewportHeight="{int(VIEW)}"',
        '    android:tint="?attr/colorControlNormal">',
        f"    <!-- {ic['key']}: {ic['note']} -->",
    ]
    if ic["basis"]:
        lines.append(f"    <!-- lineage ({ic['apps']}): {ic['basis']} -->")
    for p in ic["strokes"]:
        lines += [
            "    <path",
            '        android:fillColor="@android:color/transparent"',
            '        android:strokeColor="@android:color/white"',
            f'        android:strokeWidth="{STROKE}"',
            f'        android:strokeLineCap="{CAP}"',
            f'        android:strokeLineJoin="{JOIN}"',
            f'        android:pathData="{p.d}" />',
        ]
    for p in ic["fills"]:
        lines += [
            "    <path",
            '        android:fillColor="@android:color/white"',
        ]
        if p.evenodd:
            lines.append('        android:fillType="evenOdd"')
        lines.append(f'        android:pathData="{p.d}" />')
    lines.append("</vector>")
    return "\n".join(lines) + "\n"


def kotlin_registry(icons):
    cat_enum = ", ".join(c[0].upper() for c in CATEGORIES)
    props, entries = [], []
    for ic in icons:
        name = pascal(ic["key"])
        note = ic["note"].replace("*/", "*\\/")
        props.append(f"    /** {note} */")
        props.append(f"    val {name}: Int get() = R.drawable.{res_name(ic['key'])}")
        kw = ", ".join(f'"{k}"' for k in ic["kw"])
        entries.append(
            f'        GxIcon("{ic["key"]}", R.drawable.{res_name(ic["key"])}, '
            f"GxIconCategory.{ic['cat'].upper()}, listOf({kw})),"
        )
    return "\n".join(
        [
            "package com.hereliesaz.graffitixr.design",
            "",
            "import androidx.annotation.DrawableRes",
            "",
            "// " + GENERATED,
            "",
            "/** The families the Graffux icon set is divided into. */",
            f"enum class GxIconCategory {{ {cat_enum} }}",
            "",
            "/** One icon: its stable key, its drawable, and what it can be searched by. */",
            "data class GxIcon(",
            "    val key: String,",
            "    @param:DrawableRes val res: Int,",
            "    val category: GxIconCategory,",
            "    val keywords: List<String>,",
            ")",
            "",
            "/**",
            " * The Graffux icon set.",
            " *",
            f" * {len(icons)} glyphs on a 24-unit grid, one {STROKE}-unit stroke weight, at most one solid",
            " * mark each — the keystone, which always sits where the operation acts.",
            " *",
            " * Reference them directly (`GraffuxIcons.Brush`) or look them up by key for a picker.",
            " */",
            "object GraffuxIcons {",
            "",
            "\n".join(props),
            "",
            "    /** Every icon, in authored order — categories stay grouped. */",
            "    val all: List<GxIcon> = listOf(",
            "\n".join(entries),
            "    )",
            "",
            "    private val byKey: Map<String, GxIcon> = all.associateBy { it.key }",
            "",
            "    /** Look an icon up by its stable key, e.g. `\"layer-mask-add\"`. */",
            "    operator fun get(key: String): GxIcon? = byKey[key]",
            "",
            "    /** Every icon in one family, in authored order. */",
            "    fun inCategory(category: GxIconCategory): List<GxIcon> = all.filter { it.category == category }",
            "",
            "    /** Case-insensitive search across keys and keywords, for an icon picker. */",
            "    fun search(query: String): List<GxIcon> {",
            "        val q = query.trim().lowercase()",
            "        if (q.isEmpty()) return all",
            "        return all.filter { icon ->",
            "            icon.key.contains(q) || icon.keywords.any { it.contains(q) }",
            "        }",
            "    }",
            "}",
            "",
        ]
    )


# ---------------------------------------------------------------------------------------
# Contact sheet
# ---------------------------------------------------------------------------------------

SHEET_CSS = """
:root {
  --ink: #f2f2f0; --ground: #0d0d0f; --dim: #74747c; --rule: #22222a;
  --hot: #ff3b1f; --cool: #2f6bff; --card: #131318;
}
@media (prefers-color-scheme: light) {
  :root { --ink: #14141a; --ground: #f7f7f5; --dim: #6c6c74; --rule: #dedee4; --card: #ffffff; }
}
:root[data-theme="light"] { --ink: #14141a; --ground: #f7f7f5; --dim: #6c6c74; --rule: #dedee4; --card: #fff; }
:root[data-theme="dark"] { --ink: #f2f2f0; --ground: #0d0d0f; --dim: #74747c; --rule: #22222a; --card: #131318; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--ground); color: var(--ink);
  font: 14px/1.5 ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif; }
.wrap { max-width: 1180px; margin: 0 auto; padding: 40px 20px 96px; }
header { border-bottom: 1px solid var(--rule); padding-bottom: 22px; margin-bottom: 26px; }
h1 { font-size: 26px; margin: 0 0 6px; letter-spacing: -0.015em; }
.sub { color: var(--dim); font-size: 13px; margin: 0; }
.meta { display: flex; flex-wrap: wrap; gap: 8px 22px; margin-top: 16px;
  font: 11px/1.4 ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--dim); }
.meta b { color: var(--ink); font-weight: 600; }
.controls { position: sticky; top: 0; z-index: 5; background: var(--ground);
  padding: 12px 0; border-bottom: 1px solid var(--rule); margin-bottom: 26px;
  display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }
input[type=search] { flex: 1 1 240px; min-width: 0; background: var(--card); color: var(--ink);
  border: 1px solid var(--rule); border-radius: 7px; padding: 9px 12px; font-size: 14px; }
input[type=search]:focus { outline: 2px solid var(--cool); outline-offset: -1px; }
.toggle { display: inline-flex; align-items: center; gap: 7px; color: var(--dim); font-size: 12px;
  background: var(--card); border: 1px solid var(--rule); border-radius: 7px; padding: 8px 12px; cursor: pointer; }
h2 { font-size: 12px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--dim);
  margin: 38px 0 4px; font-weight: 600; }
h2 .n { color: var(--hot); }
.blurb { color: var(--dim); font-size: 12px; margin: 0 0 16px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(116px, 1fr)); gap: 6px; }
.cell { background: var(--card); border: 1px solid var(--rule); border-radius: 9px;
  padding: 14px 8px 10px; text-align: center; overflow: hidden; }
.cell .art { display: flex; align-items: flex-end; justify-content: center; gap: 10px; height: 34px; }
.cell svg { color: var(--ink); display: block; }
.cell .k { margin-top: 9px; font: 10px/1.35 ui-monospace, SFMono-Regular, Menlo, monospace;
  color: var(--dim); word-break: break-word; }
.cell .apps { font: 9px/1 ui-monospace, monospace; margin-top: 4px; letter-spacing: .06em;
  color: color-mix(in srgb, var(--dim) 55%, transparent); }
.cell:hover { border-color: var(--cool); }
.cell:hover .k { color: var(--ink); }
body.grid-on .cell .art { background-image:
  linear-gradient(to right, color-mix(in srgb, var(--cool) 22%, transparent) 1px, transparent 1px),
  linear-gradient(to bottom, color-mix(in srgb, var(--cool) 22%, transparent) 1px, transparent 1px);
  background-size: 4px 4px; background-position: center bottom; }
.empty { color: var(--dim); padding: 40px 0; text-align: center; }
footer { margin-top: 56px; padding-top: 18px; border-top: 1px solid var(--rule);
  color: var(--dim); font-size: 11px; font-family: ui-monospace, monospace; }
"""

SHEET_JS = """
const q = document.getElementById('q');
const cells = [...document.querySelectorAll('.cell')];
const sections = [...document.querySelectorAll('section')];
function apply() {
  const v = q.value.trim().toLowerCase();
  cells.forEach(c => { c.hidden = v !== '' && !c.dataset.s.includes(v); });
  sections.forEach(s => {
    const shown = [...s.querySelectorAll('.cell')].filter(c => !c.hidden).length;
    s.hidden = shown === 0;
    const n = s.querySelector('h2 .n'); if (n) n.textContent = shown;
  });
  document.getElementById('empty').hidden = cells.some(c => !c.hidden);
}
q.addEventListener('input', apply);
document.getElementById('gridToggle').addEventListener('click', () => {
  document.body.classList.toggle('grid-on');
});
"""


def contact_sheet(icons):
    by_cat = {}
    for ic in icons:
        by_cat.setdefault(ic["cat"], []).append(ic)

    out = [
        "<title>Graffux Icons</title>",
        f"<style>{SHEET_CSS}</style>",
        '<div class="wrap">',
        "<header>",
        "<h1>Graffux icon set</h1>",
        '<p class="sub">One stroke weight, one grid, one solid mark per glyph. '
        "Built for a phone screen at arm's length.</p>",
        '<div class="meta">'
        f"<span><b>{len(icons)}</b> icons</span>"
        f"<span><b>{len(by_cat)}</b> families</span>"
        f"<span>grid <b>{int(VIEW)}×{int(VIEW)}</b></span>"
        f"<span>live area <b>{int(LIVE[0])}–{int(LIVE[1])}</b></span>"
        f"<span>stroke <b>{STROKE}</b></span>"
        f"<span>cap/join <b>{CAP}</b></span>"
        "</div>",
        "</header>",
        '<div class="controls">',
        '<input id="q" type="search" placeholder="Search name, keyword, or family…" autocomplete="off">',
        '<button class="toggle" id="gridToggle" type="button">4-unit grid</button>',
        "</div>",
    ]

    for key, title, blurb in CATEGORIES:
        group = by_cat.get(key, [])
        if not group:
            continue
        out.append(f'<section data-cat="{key}">')
        out.append(f'<h2>{html.escape(title)} · <span class="n">{len(group)}</span></h2>')
        out.append(f'<p class="blurb">{html.escape(blurb)}</p>')
        out.append('<div class="grid">')
        for ic in group:
            search = " ".join([ic["key"], key, title, ic["apps"], ic["basis"], *ic["kw"]]).lower()
            tip_text = ic["note"] + (f"\nLineage ({ic['apps']}): {ic['basis']}" if ic["basis"] else "")
            body24 = svg_body(ic, indent="")
            svg_attrs = (
                f'viewBox="0 0 {int(VIEW)} {int(VIEW)}" fill="none" stroke="currentColor" '
                f'stroke-width="{STROKE}" stroke-linecap="{CAP}" stroke-linejoin="{JOIN}"'
            )
            out.append(
                f'<div class="cell" data-s="{html.escape(search, quote=True)}" '
                f'title="{html.escape(tip_text, quote=True)}">'
                f'<div class="art">'
                f'<svg width="24" height="24" {svg_attrs}>{body24}</svg>'
                f'<svg width="16" height="16" {svg_attrs}>{body24}</svg>'
                f"</div>"
                f'<div class="k">{html.escape(ic["key"])}</div>'
                f'<div class="apps">{html.escape(ic["apps"])}</div>'
                "</div>"
            )
        out.append("</div></section>")

    out += [
        '<p class="empty" id="empty" hidden>Nothing matches that.</p>',
        "<footer>Each cell shows the glyph at 24px and at 16px. "
        "If it only works at 24, it does not work.</footer>",
        "</div>",
        f"<script>{SHEET_JS}</script>",
    ]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------


def clean_stale(icons):
    """Remove drawables from a previous run whose icon no longer exists."""
    live = {res_name(ic["key"]) + ".xml" for ic in icons}
    removed = 0
    if os.path.isdir(DRAWABLE_DIR):
        for fn in os.listdir(DRAWABLE_DIR):
            if fn.startswith(PREFIX) and fn not in live:
                os.remove(os.path.join(DRAWABLE_DIR, fn))
                removed += 1
    if os.path.isdir(SVG_DIR):
        live_svg = {ic["key"] + ".svg" for ic in icons}
        for fn in os.listdir(SVG_DIR):
            if fn.endswith(".svg") and fn not in live_svg:
                os.remove(os.path.join(SVG_DIR, fn))
    return removed


def main():
    errors, warnings = validate(ICONS)
    for w in warnings:
        print(f"  warn  {w}")
    if errors:
        for e in errors:
            print(f"  ERROR {e}", file=sys.stderr)
        return 1

    os.makedirs(SVG_DIR, exist_ok=True)
    os.makedirs(DRAWABLE_DIR, exist_ok=True)

    stale = clean_stale(ICONS)

    for ic in ICONS:
        with open(os.path.join(SVG_DIR, ic["key"] + ".svg"), "w", encoding="utf-8") as fh:
            fh.write(svg_document(ic))
        with open(os.path.join(DRAWABLE_DIR, res_name(ic["key"]) + ".xml"), "w", encoding="utf-8") as fh:
            fh.write(vector_drawable(ic))

    manifest = {
        "grid": {"view": VIEW, "live": list(LIVE), "stroke": STROKE, "cap": CAP, "join": JOIN},
        "categories": [{"key": k, "title": t, "blurb": b} for k, t, b in CATEGORIES],
        "icons": [
            {
                "key": ic["key"],
                "category": ic["cat"],
                "drawable": res_name(ic["key"]),
                "keywords": ic["kw"],
                "apps": ic["apps"],
                "basis": ic["basis"],
                "note": ic["note"],
            }
            for ic in ICONS
        ],
    }
    with open(os.path.join(DIST, "icons.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    with open(os.path.join(DIST, "contact-sheet.html"), "w", encoding="utf-8") as fh:
        fh.write(contact_sheet(ICONS))

    os.makedirs(os.path.dirname(KOTLIN_PATH), exist_ok=True)
    with open(KOTLIN_PATH, "w", encoding="utf-8") as fh:
        fh.write(kotlin_registry(ICONS))

    counts, weights = {}, []
    for ic in ICONS:
        counts[ic["cat"]] = counts.get(ic["cat"], 0) + 1
        weights.append((sum(len(p.d) for p in ic["strokes"] + ic["fills"]), ic["key"]))
    weights.sort(reverse=True)
    print(f"\n{len(ICONS)} icons across {len(counts)} families"
          + (f", {stale} stale drawable(s) removed" if stale else ""))
    for k, t, _ in CATEGORIES:
        if k in counts:
            print(f"  {counts[k]:>4}  {t}")
    total = sum(w for w, _ in weights)
    print(f"\npath data: {total} chars total, {total // len(weights)} mean, "
          f"heaviest {weights[0][1]} at {weights[0][0]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
