from pathlib import Path

p = Path('feature/editor/src/main/java/com/hereliesaz/graffitixr/feature/editor/EditorViewModel.kt')
s = p.read_text()

s = s.replace(
'''    private val basicPendingDabs = AzphaltPendingBatchQueue<BrushDab>()\n''',
'''    // Preserve drawCurveRun boundaries: stampDabs(buildUp=false) max-combines within one call,\n    // so flattening multiple curve runs into one scheduler batch would change low-opacity Basic\n    // Brush pixels depending on how quickly the worker drained.\n    private val basicPendingDabs = AzphaltPendingBatchQueue<List<BrushDab>>()\n''', 1)

old = '''        if (activeToolForCadence == Tool.BRUSH) {\n            addStrokePoint(stabilizedPoint, stabilizedPressure)\n            if (!azphaltRenderCadence.shouldRender(nowMs, rateHz)) return\n        } else {\n'''
new = '''        if (activeToolForCadence == Tool.BRUSH) {\n            addStrokePoint(stabilizedPoint, stabilizedPressure)\n            // Stamp brushes can reconstruct every not-yet-previewed sample from canonical history\n            // on the next displayed frame. Basic Brush advances a stateful Catmull-Rom window and\n            // width recursion per point instead, so feed every physical sample into that cheap\n            // geometry path and let its background worker coalesce only the expensive rendering.\n            if (stampBrushForStroke != null && !azphaltRenderCadence.shouldRender(nowMs, rateHz)) return\n        } else {\n'''
assert old in s
s = s.replace(old, new, 1)

s = s.replace('''        basicPendingDabs.append(dabs)\n''', '''        basicPendingDabs.append(dabs)\n''', 1)

old = '''                    val batch = synchronized(basicLiveLock) {\n                        if (strokeGeneration != generation || strokeLayerId != layerId) return@launch\n                        basicPendingDabs.drain()\n                    }\n                    if (batch.isEmpty()) {\n'''
new = '''                    val groups = synchronized(basicLiveLock) {\n                        if (strokeGeneration != generation || strokeLayerId != layerId) return@launch\n                        basicPendingDabs.drain()\n                    }\n                    if (groups.isEmpty()) {\n'''
assert old in s
s = s.replace(old, new, 1)

old = '''                    var gpuHandled = false\n                    // Unlike the old input-thread call, the native fence/readback now blocks only\n                    // this single background consumer. Holding liveCurveLock for the native call\n                    // prevents onStrokeEnd/a fast redown from destroying the engine mid-submit.\n                    synchronized(liveCurveLock) {\n                        if (strokeGeneration == generation && strokeLayerId == layerId && strokeGpuActive) {\n                            val engine = strokeGpuEngine\n                            if (engine != null) {\n                                val baseAlpha = (paintSnapshot.color ushr 24) and 0xFF\n                                val combinedAlpha = (baseAlpha * paintSnapshot.alpha / 255).coerceIn(0, 255)\n                                val colorForGpu = (combinedAlpha shl 24) or (paintSnapshot.color and 0x00FFFFFF)\n                                gpuHandled = engine.stampDabs(batch, colorForGpu, 1f) && engine.readback(targetBitmap)\n                                if (!gpuHandled && strokeGpuEngine === engine) {\n                                    strokeGpuActive = false\n                                    strokeGpuEngine = null\n                                    engine.destroy()\n                                }\n                            }\n                        }\n                    }\n\n                    if (!gpuHandled) {\n                        if (strokeGeneration != generation || strokeLayerId != layerId) return@launch\n                        val cpuPaint = Paint(paintSnapshot).apply { style = Paint.Style.FILL }\n                        for (dab in batch) {\n                            canvas.drawCircle(dab.x, dab.y, dab.radius, cpuPaint)\n                        }\n                    }\n'''
new = '''                    var gpuHandled = false\n                    // Preserve the historical one-stampDabs-call-per-curve-run max-combine\n                    // semantics, but defer readback until all groups currently coalesced by the\n                    // worker have been submitted. Thus scheduling is coalesced without changing\n                    // brush appearance, and software presentation pays one readback per drain.\n                    synchronized(liveCurveLock) {\n                        if (strokeGeneration == generation && strokeLayerId == layerId && strokeGpuActive) {\n                            val engine = strokeGpuEngine\n                            if (engine != null) {\n                                val baseAlpha = (paintSnapshot.color ushr 24) and 0xFF\n                                val combinedAlpha = (baseAlpha * paintSnapshot.alpha / 255).coerceIn(0, 255)\n                                val colorForGpu = (combinedAlpha shl 24) or (paintSnapshot.color and 0x00FFFFFF)\n                                var allSubmitted = true\n                                for (group in groups) {\n                                    if (!engine.stampDabs(group, colorForGpu, 1f)) {\n                                        allSubmitted = false\n                                        break\n                                    }\n                                }\n                                gpuHandled = allSubmitted && engine.readback(targetBitmap)\n                                if (!gpuHandled && strokeGpuEngine === engine) {\n                                    strokeGpuActive = false\n                                    strokeGpuEngine = null\n                                    engine.destroy()\n                                }\n                            }\n                        }\n                    }\n\n                    if (!gpuHandled) {\n                        if (strokeGeneration != generation || strokeLayerId != layerId) return@launch\n                        val cpuPaint = Paint(paintSnapshot).apply { style = Paint.Style.FILL }\n                        for (group in groups) for (dab in group) {\n                            canvas.drawCircle(dab.x, dab.y, dab.radius, cpuPaint)\n                        }\n                    }\n'''
assert old in s
s = s.replace(old, new, 1)

p.write_text(s)
