from pathlib import Path

path = Path('app/src/main/java/com/hereliesaz/graffux/MainActivity.kt')
text = path.read_text()
old = '''    ) {\n        nestedTool(Tool.SELECT, "Select", GraffuxIcons.SelectSubject)\n        SelectionShape.entries.forEach { mode ->\n            val id = "selectShape.${mode.name}"\n            azRailItem(\n                id = id, classifiers = setOf(id),\n                text = mode.label,\n                content = when (mode) {\n                    SelectionShape.FREEHAND -> GraffuxIcons.SelectLasso\n                    SelectionShape.RECTANGLE -> GraffuxIcons.SelectRect\n                    SelectionShape.ELLIPSE -> GraffuxIcons.SelectEllipse\n                    SelectionShape.AUTOMATIC -> GraffuxIcons.SelectWand\n                },\n                color = railColor(id),\n                shape = AzButtonShape.NONE_SQUARE,\n                fillColor = railColor(id),\n                onClick = { vm.onSetSelectionShape(mode) },\n            )\n        }\n'''
new = '''    ) {\n        val selectionShapeOrder = listOf(\n            SelectionShape.RECTANGLE,\n            SelectionShape.FREEHAND,\n            SelectionShape.ELLIPSE,\n            SelectionShape.AUTOMATIC,\n        )\n        selectionShapeOrder.forEach { mode ->\n            val id = "selectShape.${mode.name}"\n            azRailItem(\n                id = id, classifiers = setOf(id),\n                text = mode.label,\n                content = when (mode) {\n                    SelectionShape.FREEHAND -> GraffuxIcons.SelectLasso\n                    SelectionShape.RECTANGLE -> GraffuxIcons.SelectRect\n                    SelectionShape.ELLIPSE -> GraffuxIcons.SelectEllipse\n                    SelectionShape.AUTOMATIC -> GraffuxIcons.SelectWand\n                },\n                color = railColor(id),\n                shape = AzButtonShape.NONE_SQUARE,\n                fillColor = railColor(id),\n                onClick = { vm.onSetSelectionShape(mode) },\n            )\n        }\n        nestedTool(Tool.SELECT, "Select", GraffuxIcons.SelectSubject)\n'''
if old not in text:
    raise SystemExit('selection rail block not found')
path.write_text(text.replace(old, new, 1))
